### ISSUE TITLE
items vanishing after sorting

### ISSUE THREAD

**Issue by ali-abz** [Tfarcenim/Dank-Storage#103]
When there are multiple items in dank storage, pressing middle click to sort items (don't recall which mod) will destroy all items except one (cobble in my case) and fill all slots with that block. Also, a good deal of the item that remains will vanish too.
using minecraft 1.16 on a single player direwolf20 modpack.

**Comment by Tfarcenim** [comment]
Don't use 3rd party mods for sorting items, use the built in button.
