### ISSUE TITLE
Dank Item dupe

### ISSUE THREAD

**Issue by XCOAnnika** [Tfarcenim/Dank-Storage#104]
The bug is in this video

Video is coming

**Comment by XCOAnnika** [comment]
https://youtu.be/qYWBW8VHbEo

**Comment by flamingram** [comment]
@XCOYoshi hopw did you do this??

**Comment by XCOAnnika** [comment]
I told you undder your Youtube commant

**Comment by flamingram** [comment]
uhmm that wasent me im a different person ive been trying but havent got it to work could you run through what you did step by step??

**Comment by Tfarcenim** [comment]
Can't reproduce, need more info

**Comment by XCOAnnika** [comment]
Fixes was a Bug with inventory tweaks
