### ISSUE TITLE
Dank storage deletes items when using building gadget's exchanger

### ISSUE THREAD

**Issue by Staegrin** [Tfarcenim/Dank-Storage#105]
https://github.com/Direwolf20-MC/BuildingGadgets/issues/615
**Building Gadgets version**
buildinggadgets-1.16.5-3.8.0
dankstorage-3.14

**Forge version**
forge: 36.0.39

**How to reproduce the issue**
Happens when using the exchanging gadget. When exchanging more than 1 block only one 1 item gets placed in the dank storage and the rest gets deleted.

*Please provide use with a step by step description*
example dank storage contains 5067 astral sorcery marble
![2021-02-24_17 19 27](https://user-images.githubusercontent.com/8494635/109030879-7e537b80-76c4-11eb-9d95-48d6fb425352.png)
exchange 9 in world with stone
![2021-02-24_17 20 11](https://user-images.githubusercontent.com/8494635/109030956-91664b80-76c4-11eb-97a3-0a8a8b36c46e.png)
marble in dank storage has gone up 1 to 5068 and 8 were deleted
![2021-02-24_17 21 25](https://user-images.githubusercontent.com/8494635/109031165-bd81cc80-76c4-11eb-80cf-a23e7daaa1d9.png)

**Comment by Staegrin** [comment]
Still a problem in new 3.15 version

**Comment by chimericdream** [comment]
I created a minimal pack to reproduce this. It includes:

JEI: 7.7.1.111
Building Gadgets: 3.8.0
Dank Storage: 3.16

I can confirm that it is still an issue. Attached are several screenshots and (if GitHub will let me) a zip file with the exported pack from the CurseForge launcher.

[CurseForge profile export (ZIP)](https://github.com/Tfarcenim/Dank-Storage/files/6872830/BG%2BDank.Bug.zip)

### Before
**1023 stone, 1024 grass, filtered pickup enabled**

![2021-07-24_12 26 40](https://user-images.githubusercontent.com/198075/126876637-e6fba67f-8dd5-4e66-b07c-cb8a6b3fe3c1.png)

![2021-07-24_12 26 44](https://user-images.githubusercontent.com/198075/126876638-4cab48e0-bfbe-49cb-8d34-d9485f6e5c35.png)

![2021-07-24_12 27 55](https://user-images.githubusercontent.com/198075/126876639-b881d2af-70e2-4f68-a101-5bcba9300976.png)

### The Exchange
Note the enchantment glint on the gadget. It has silk touch, so it should pick up all of the grass.

![2021-07-24_12 28 00](https://user-images.githubusercontent.com/198075/126876640-05dca980-0c72-4c89-b359-338d6ef8d740.png)

![2021-07-24_12 28 02](https://user-images.githubusercontent.com/198075/126876642-e08a80dd-939f-42c4-a0ba-819623ef8eec.png)

![2021-07-24_12 28 03](https://user-images.githubusercontent.com/198075/126876643-d638c5d8-9ac9-4902-a38b-42f79cc43c02.png)

![2021-07-24_12 28 05](https://user-images.githubusercontent.com/198075/126876644-2bec5452-9929-4aa0-9636-6999e4e6cf2c.png)

### After
**1025 grass, 998 stone**

![2021-07-24_12 28 11](https://user-images.githubusercontent.com/198075/126876645-07de8411-1785-4363-a704-0d2dac290aa0.png)

![2021-07-24_12 28 13](https://user-images.githubusercontent.com/198075/126876647-1c45d145-2577-4de9-801a-f163a769f34d.png)

**Comment by chimericdream** [comment]
Have you had a chance to look into this? I know you have a fair number of mods to maintain, but hopefully the screenshots and pack export are helpful for diagnosing and fixing whatever underlying issue is causing the bug. Thanks!

**Comment by Tfarcenim** [comment]
> Have you had a chance to look into this? I know you have a fair number of mods to maintain, but hopefully the screenshots and pack export are helpful for diagnosing and fixing whatever underlying issue is causing the bug. Thanks!

I've got more than just mods to maintain, I have actual jobs now.

That being said, I just got done rewriting almost the entire mod again so I won't be visiting this in 1.16.
