### ISSUE TITLE
Server crash Ticking Entity

### ISSUE THREAD

**Issue by Varijon** [Tfarcenim/Dank-Storage#106]
Twice we had the server crash with the following error:
[Crash](https://gist.github.com/Varijon/9c5c3d6eb959b7e891dfa08d8b982e3c)

I will update the issue once the users tell me what exactly they're doing with the dank.

edit: Apparently it's caused by someone removing the dank from the dock while someone has the gui open.

**Comment by Tfarcenim** [comment]
confirmed
