### ISSUE TITLE
shift clicking locked slots

### ISSUE THREAD

**Issue by Deragonis** [Tfarcenim/Dank-Storage#108]
shift-clicking a locked slot removes the locked item, making it a blank slot, I use different danks for stones and ores and id like to be able to lock the ores into the dank null and not have them all taken out when I shift-click on them, having it no longer have the item locked makes it difficult to do so

**Comment by Tfarcenim** [comment]
Confirmed, but shift clicking code is a disaster and I'm not eager to fix it right now.

**Comment by PINPAL** [comment]
Also applies to locked slots interacting with hoppers and using them in construction mode, locked slots do virtually nothing.

**Comment by Tfarcenim** [comment]
Implemented a proper fix in the 1.18+ versions, if someone wants to backport the commit, I'll merge it in, but all focus is on 1.18 and up from now on.
