### ISSUE TITLE
Feature Request: Colored Dank Nulls

### ISSUE THREAD

**Issue by Gerdathlete** [Tfarcenim/Dank-Storage#111]
Currently there aren't visual ways of differentiating between different dank nulls in your inventory. You can only use names which require the user to hover over the item to find which dank they are looking for. 

Instead, if danks could be colored using dyes similar to the way shulkers are dyed, you could tell the difference between multiple danks at a glance.

**Comment by Tfarcenim** [comment]
They're already colored differently based on tier, adding another layer of coloring on that would be a disaster
