### ISSUE TITLE
Feature Request: Item Preview Gui

### ISSUE THREAD

**Issue by Gerdathlete** [Tfarcenim/Dank-Storage#112]
A great addition to this mod would be a item preview gui that can be seen when hovering over a dank null.

Here's an example of an item preview gui used to show the content of a shulker box:
![image](https://user-images.githubusercontent.com/25123577/114962815-480ebe80-9e20-11eb-9a89-e4bbba13bb49.png)

**Comment by Tfarcenim** [comment]
saved for 1.17

**Comment by Tfarcenim** [comment]
I meant 1.18

**Comment by Tfarcenim** [comment]
This isn't even possible in 1.16, and it's already implemented in dev for 1.18 so imma gonna go ahead and close this now
