### ISSUE TITLE
Having a dank anywhere in inventory prevents some insert-into-tileentity operations for other blocks

### ISSUE THREAD

**Issue by Xetaxheb** [Tfarcenim/Dank-Storage#113]
https://github.com/CyclopsMC/IntegratedDynamics/issues/1016

This is the only example I have currently so I don't know which end it's on but they think yours.
Reproducible, having a dank in the inventory period prevents right clicking anything into the squeezer, but this likely appears elsewhere.

**Comment by Tfarcenim** [comment]
oh no

**Comment by Linguardium** [comment]
This appears to only be an issue when the dank is set to pick up.  I can either remove the dank from the inventory (backpack, drop, etc) or turn pickup off and suddenly the things work again

**Comment by aaronhowser1** [comment]
I also have this issue, dropping the dank on the ground lets me put items in the ID Squeezer

**Comment by Tfarcenim** [comment]
No longer a thing in 3.19
