### ISSUE TITLE
Item pickup priority overridden by quantumstorage bags

### ISSUE THREAD

**Issue by Xetaxheb** [Tfarcenim/Dank-Storage#114]
Similar to this: https://github.com/Tfarcenim/Dank-Storage/issues/56
When they have autopickup enabled, i'm not sure dank gets a chance to intercept items. Ideally it would since it's a "specific" storage rather than a general one though i'm not sure whose end needs fixing.

https://www.curseforge.com/minecraft/mc-mods/quantumstorage
https://github.com/gigabit101/QuantumStorage

**Comment by Tfarcenim** [comment]
Interesting, I thought I intercepted everything

**Comment by Tfarcenim** [comment]
It's weird and inconsistent in who takes priority, since I don't want to mess with another mod, the solution here is to not have both on autopickup.
