### ISSUE TITLE
Crash when dropping a dank.

### ISSUE THREAD

**Issue by LocalBoomer** [Tfarcenim/Dank-Storage#115]
Crash when dropping a dank with the default 'q to drop' button. Doesn't happen always but quite frequently. Mentions something about Numina's Renderer I think?

[Crash Report](https://pastebin.com/JnuxH8Ez)

I've got two more reports but they're all the same. Can't cast air to dank.

P.S. What a day when I get to title an issue 'dropping a dank'.

**Comment by Famous5000** [comment]
> Crash when dropping a dank with the default 'q to drop' button. Doesn't happen always but quite frequently. Mentions something about Numina's Renderer I think?
> 
> [Crash Report](https://pastebin.com/JnuxH8Ez)
> 
> I've got two more reports but they're all the same. Can't cast air to dank.
> 
> P.S. What a day when I get to title an issue 'dropping a dank'.

I have also run into this problem when using Numina. This is likely an issue on their end, unfortunately.

EDIT: The issue was fixed after removing their mod and Modular Powersuits, which was being a buggy mod anyways, which was unfortunate since that was a mod I used to love enjoying.

**Comment by LocalBoomer** [comment]
Rip, If you're interested Mekanism's new mekasuit seems to be based on the IC2 powersuit which is what MPS itself is based off. Not quite as flashy or comprehensive but not a bad alternative mod and OP as all hell.

**Comment by Famous5000** [comment]
> Rip, If you're interested Mekanism's new mekasuit seems to be based of the IC" powersuit which is what MPS itself is based off. Not quite as flashy or comprehensive but not a bad alternative nod OP as all hell.

I absolutely loved Mekanism's Mekasuits, even though I haven't been able to try them out in survival haha, though they seem to be the perfect replacement to MPS that I needed. So yeah, I've been playing with that for a while, trying to get the suits through a mostly survival run, though it's been pretty rough starting from ground zero.

**Comment by ProsperCraft** [comment]
Same - https://gist.github.com/ProsperCraft/303594c87f148a656d99776a41d7cec9
1.16.5
dankstorage-3.16
forge-1.16.5-36.2.22
Numina-1.16.5-2.1.16
ModularPowersuits-1.16.5-2.1.18

**Comment by lehjr** [comment]
> Same - https://gist.github.com/ProsperCraft/303594c87f148a656d99776a41d7cec9 1.16.5 dankstorage-3.16 forge-1.16.5-36.2.22 Numina-1.16.5-2.1.16 ModularPowersuits-1.16.5-2.1.18

That's not on my end. That's from DankHandler extending the ItemStackHandler capability but not being filtered with something like
.filter(IDankHandler.class::isInstance).map(DankHandler.class::cast)
