### ISSUE TITLE
Dock

### ISSUE THREAD

**Issue by Logics2996** [Tfarcenim/Dank-Storage#116]
How do i get the Dock to Import into My ME System

**Comment by LocalBoomer** [comment]
You need something to import it with like an importer or import bus (depending on which mods ME system you're using)

**Comment by Logics2996** [comment]
Applied energistics, iv tried the storage bus and an import and export bus but none are working

**Comment by Logics2996** [comment]
so its pulling as long as i put the item i want to pull into the export bus, but iv seen people do it where it does everything at once

**Comment by Logics2996** [comment]
so its pulling as long as i put the item i want to pull into the export bus, but iv seen people do it where it does everything at once

**Comment by LocalBoomer** [comment]
Is the bus in whitelist mode?

**Comment by LocalBoomer** [comment]
I've just tried it in my world and an import bus on a dock with a dank in will pull items into a chest I have with a storage bus on it. Are there any intricacies to how your system is set up?

**Comment by Logics2996** [comment]
can you send me a screenshot of your setup and how do you put an import bus on whitelist mode

**Comment by LocalBoomer** [comment]
Whitelist mode doesn't seem to be an option on import busses (guessed it might be as it is in Refined Storage. 
![2021-05-04_23 45 35](https://user-images.githubusercontent.com/13005453/117079025-e19c0280-ad32-11eb-81f3-f469331f7180.png) Ignore the TOP error that's unrelated to anything but that is just an import bus, energy acceptor, controller and storage bus with a dock and chest on either end.

Edit:
Here are the screens for the busses

![2021-05-04_23 48 14](https://user-images.githubusercontent.com/13005453/117079226-47888a00-ad33-11eb-8615-19cedb13001a.png)
![2021-05-04_23 48 31](https://user-images.githubusercontent.com/13005453/117079231-48212080-ad33-11eb-91c2-3e61395d05c8.png)

**Comment by Logics2996** [comment]
what cables are you using?

**Comment by LocalBoomer** [comment]
Fluix smart cable

**Comment by LocalBoomer** [comment]
Are you exceeding channel limits on your cable?

**Comment by Logics2996** [comment]
this is my set up

![1](https://user-images.githubusercontent.com/83439271/117079534-db5a5600-ad33-11eb-9999-0e1dd352d65b.png)

**Comment by LocalBoomer** [comment]
Ah that's the problem.

You have a bus on either side. You should only have the bus on the dock side and the cable should go directly into the controller. You may need a bus or something on the other side but the cables should connect to the controller itself without any intermediary.

**Comment by Logics2996** [comment]
![3](https://user-images.githubusercontent.com/83439271/117079721-3b50fc80-ad34-11eb-9b54-78726b6a78d2.png)
 iv done it like that and its still not working, its confusing me to hell lmao

**Comment by LocalBoomer** [comment]
What are you trying to put it into? ME Drives or something else?

**Comment by Logics2996** [comment]
yeah me drive

**Comment by LocalBoomer** [comment]
and there is have space for that type of item and items in general?

**Comment by Logics2996** [comment]
yes i have 4 16k drive empty

**Comment by LocalBoomer** [comment]
Hang on you need to use an import bus to move stuff into the system. Storage bus allows the system to access stuff in the attached  inventory but doesn't actively move it. Kinda like turning the block connected into an ME Drive itself.

**Comment by Logics2996** [comment]
yeah iv dont that and still not working :(

**Comment by Logics2996** [comment]
![1](https://user-images.githubusercontent.com/83439271/117080585-1493c580-ad36-11eb-890d-1663dd4d44bd.png)
![2](https://user-images.githubusercontent.com/83439271/117080587-152c5c00-ad36-11eb-9cce-364ee024657a.png)
![3](https://user-images.githubusercontent.com/83439271/117080588-15c4f280-ad36-11eb-956c-8ca677c416d6.png)
![4](https://user-images.githubusercontent.com/83439271/117080593-165d8900-ad36-11eb-96d0-93fa848efb04.png)

**Comment by LocalBoomer** [comment]
Can you show me the Drive as well? And if possible can you put some smart cable for that as well so I can see the channel count is in order?

**Comment by Logics2996** [comment]
![1](https://user-images.githubusercontent.com/83439271/117080846-8f5ce080-ad36-11eb-9e61-eee6b68f3f8a.png)
![2](https://user-images.githubusercontent.com/83439271/117080847-8ff57700-ad36-11eb-9c59-17028e06dcc1.png)
![3](https://user-images.githubusercontent.com/83439271/117080851-9126a400-ad36-11eb-9cb1-c95cb1b1b48a.png)
 there my drives, how do you see channel count

**Comment by LocalBoomer** [comment]
If you put smart cable instead of the normal glass one it shows lines for each channel.

**Comment by Logics2996** [comment]
want me to change all the fluix cables for smart?

**Comment by LocalBoomer** [comment]
I'd recommend it normally but for now just the ones that connect to the Controller and the Drives themselves.

**Comment by Logics2996** [comment]
![1](https://user-images.githubusercontent.com/83439271/117081189-55d8a500-ad37-11eb-8ec2-83f8e984f0b0.png)
![2](https://user-images.githubusercontent.com/83439271/117081196-57a26880-ad37-11eb-9182-85b7aa91b1ce.png)
![3](https://user-images.githubusercontent.com/83439271/117081197-583aff00-ad37-11eb-82d5-20ab574d7246.png)
there all them

**Comment by LocalBoomer** [comment]
Also if you hover over the drives are any of them going up? I just noticed you have a lot of cobble and without acceleration cards the busses can be quite slow.

**Comment by Logics2996** [comment]
since going to smart cables its smarting to go in now thank you very much :), its slow, how do i do it faster

**Comment by Logics2996** [comment]
where do i put the acceleration cards, in the import bus?

**Comment by LocalBoomer** [comment]
Acceleration cards in the import bus. Also if you run out of channels look into P2P tunnels and Dense cable. P2P tunnels allow for 32 channels to be transmitted over one channel and are a fun rabbit hole of their own while Dense cable also allows for 32 channels (it's literally  4 normal cables "glued" together) but cannot connect directly to most devices except a controller. (just put a piece of glass, covered or smart cable on the device then the dense cable onto that.)

**Comment by Logics2996** [comment]
nice, next thing on my list is to make an automated warehouse so thats good to know, also, are the back ones channels that have been taken

**Comment by LocalBoomer** [comment]
So the light coloured lines are channels 1 through 4 and the bright ones are 5 through 8. Dense does the same but each line represents 4 channels instead of one. The black part just means channels are available. Black cable uses a dark grey for channels even though it says it's black.

**Comment by Logics2996** [comment]
so black is channels that are available and grey/white is channels that are taken?

**Comment by LocalBoomer** [comment]
Yeah but the colour of the taken channels depends on the colour the cable is dyed.

**Comment by Logics2996** [comment]
ahh okay, im just going to stick to white to make it easier
