### ISSUE TITLE
Tag inconsistencies

### ISSUE THREAD

**Issue by LocalBoomer** [Tfarcenim/Dank-Storage#117]
I've got a dank I'm using just for ores and it seems to randomly decide some items will merge when picking up items with the same tag and other times it won't. I'm mainly having issues with uranium and aluminium ores but other ores like copper and lead seem to work fine.

**Comment by Tfarcenim** [comment]
It's not random, the items are either tagged incorrectly, or another tag is taking priority.

**Comment by Tfarcenim** [comment]
I'm going to go ahead and close this now
