### ISSUE TITLE
Possible dupe glitch / cross-mod interaction with Upsizer mod

### ISSUE THREAD

**Issue by chimericdream** [Tfarcenim/Dank-Storage#118]
We have both this mod and Upsizer in a custom pack. Our community spawn area is a mushroom island, so I have been using soup (stacked to 16 via Upsizer) as my primary early-game food source. I was keeping both the soup and empty bowls in a dank, but I noticed that whenever I would eat, the dank would _add_ several bowls of soup in addition to picking up the empty bowl. As best I can tell, it "picks up" a number of bowls matching whatever is left in the stack. So if I have 16 and eat 1, the dank will increase the soup it has stored by 15. I wound up going from ~100 bowls of soup to well over 1000 before my brain registered what was happening.

**Comment by Tfarcenim** [comment]
Soups and other food items that spit out items don't behave properly at all if patched to have stacksizes > 1, this is not a fault of Dank Storage, but rather on Upsizer for not fixing the vanilla bug.

Oh cool, it's closed source so I can't even see what's wrong, classic.  Go yell at them.

**Comment by chimericdream** [comment]
Thanks for the reply. I'll report this to the Upsizer dev(s).
