### ISSUE TITLE
Bug with DankNull

### ISSUE THREAD

**Issue by NielsPilgaard** [Tfarcenim/Dank-Storage#119]
You can use danks to duplicate stackable items indefinitely by placing two of an item in a dank and filling up your inventory completely then ctrl right clicking the item you want to duplicate that is inside the dank.

- dankstorage-3.16
- https://github.com/NillerMedDild/Enigmatica6/issues/2218

**Comment by Tfarcenim** [comment]
Hmm, ctrl right click should be locking slots, not dupllicating items, time to see if this is an actual bug or just inventory management mods being bad as usual.

**Comment by Tfarcenim** [comment]
I already had to ban quark from placing buttons on them because they never fixed the dupe bug from their broken inventory transfer.

**Comment by Tfarcenim** [comment]
I'm going with the latter because this is not reproducible in a clean instance.

**Comment by NielsPilgaard** [comment]
Hmm damn. Sorry for the report then.
