### ISSUE TITLE
New configuration suggestion and dupe Fix

### ISSUE THREAD

**Issue by Ki-Tan2934** [Tfarcenim/Dank-Storage#121]
Allow to blacklist items from being interacted or to disable construct mode due to a dupe glitch with backpacks

Example on how the dupe works [](https://github.com/AllTheMods/ATM-6/issues/1092)

**Comment by Tfarcenim** [comment]
> blacklist items from being interacted
This has been possible for several versions
> dupe glitch with backpacks
Sure it's not the backpack mod's fault? They're notorious for duping.

**Comment by Ki-Tan2934** [comment]
Guess my Example Link did not work sorry about that. here is the Example
https://github.com/AllTheMods/ATM-6/issues/1092

**Comment by Ki-Tan2934** [comment]
Might affect other containers as well but if you could blacklist their mod and allow us to add blacklisted items with a tag we could fix it.

**Comment by Tfarcenim** [comment]
They can already be blacklisted in the current version using the tag
https://github.com/Tfarcenim/Dank-Storage/blob/1.15.x/src/main/resources/data/dankstorage/tags/items/blacklisted_usage.json

I'm not adding any more pre-emptive blacklists until 1.17 as I am about to rewrite a good portion of the mod.

**Comment by Ki-Tan2934** [comment]
So adding that Tag to an item will blacklist it?

**Comment by Tfarcenim** [comment]
yes

**Comment by Ki-Tan2934** [comment]
Seems adding the tag does not work and you can still put the backpacks inside each other
https://imgur.com/a/fl27KfP

**Comment by Tfarcenim** [comment]
then just blacklist them from being stored altogether, sounds like they use an unconventional opening method

**Comment by Ki-Tan2934** [comment]
Gonna be dumb and ask how, it's just the construction part that causes the problem

**Comment by Tfarcenim** [comment]
I had a closer look, you have it in the wrong tag, it should be in `dankstorage:blacklisted_usage`

**Comment by Ki-Tan2934** [comment]
Thanks problem solved
