### ISSUE TITLE
Suggestion: 1 point Durability storage

### ISSUE THREAD

**Issue by Thunder-Nova** [Tfarcenim/Dank-Storage#122]
Having dank storage be able to store multiple items with durability, at 1 point of durability. 

There should be a blacklist for durability conversion. Due that some mods apply it even though it doesn't use any.

The big reason behind this is mostly removing clutter from farming. Such as bows, armors, and swords, etc. from mob drops and fishing.

**Comment by Xetaxheb** [comment]
they still have nbt data which is the larger issue and seems out of scope for an item designed for placing blocks

what you're looking for is a backpack with filtered pickups that can ignore nbt data

**Comment by Tfarcenim** [comment]
> Having dank storage be able to store multiple items with durability, at 1 point of durability.

This is already possible if they're the exact same item.

> There should be a blacklist for durability conversion. Due that some mods apply it even though it doesn't use any.

The most I will add is a flag to match/ignore nbt, nothing more specific will be added.

**Comment by Tfarcenim** [comment]
On second thought, no.  This items is supposed to be for storage, not a poor substitute for filtered pipes
