### ISSUE TITLE
(1.17) Crash upon using construction mode

### ISSUE THREAD

**Issue by SushiRay** [Tfarcenim/Dank-Storage#123]
[crash-2021-06-26_18.40.30-client.txt](https://github.com/Tfarcenim/Dank-Storage/files/6720079/crash-2021-06-26_18.40.30-client.txt)

When dank is set to construction mode, it defaults to no block, and causes crash upon attempting to place one.

**Comment by Tfarcenim** [comment]
Wrong repo, this is for forge, not fabric
