### ISSUE TITLE
Dupe Glitch

### ISSUE THREAD

**Issue by TheTechPny** [Tfarcenim/Dank-Storage#125]
If you open a Dank and drop it at the same time, you can remove the items on the GUI while the dank on the ground will still have them.

**Comment by Tfarcenim** [comment]
This is not possible, the dank immediately closes once the item in the hand no longer matches the item when opening the gui.

**Comment by TheTechPny** [comment]
You are wrong.
https://www.youtube.com/watch?v=PuKoTXPjPOk

I forgot to pick it back up and open it in the video but it still has the item inside it. I can upload another video if you'd like.

**Comment by Tfarcenim** [comment]
Now do it in an instance with 0 other mods, I will only reopen this if it doable on the latest version (3.16 as of this comment).

**Comment by TheTechPny** [comment]
Simply join a server that is NOT hosted on the local network. Having ONLY dank storage mod but hosting the server externally allows for replication of this dupe.

**Comment by Tfarcenim** [comment]
So what I've been getting from other modders is that this is more likely to be desync than actual duping.  Given the nature of this bug and the inability to get a reproduction of actual duping rather than desync, this will remain closed.

**Comment by TheTechPny** [comment]
I don't understand what you mean. You can't replicate this on your own? I have a server hosted on a dedicated machine and my ping is sub 60ms. The server only has the newest version of forge and dank storage and the dupe works. I don't know what you mean by it's desync rather than actual duping, the items you dupe are real and can be crafted with.

If you need a server to test it with I can provide you with one
