### ISSUE TITLE
Dock Deleting Dank

### ISSUE THREAD

**Issue by Larsenist** [Tfarcenim/Dank-Storage#126]
When removing a Dank from the Dock, it just disappears instead of dropping or going into your inventory

https://user-images.githubusercontent.com/61611233/125844148-314525ff-4acd-403a-919d-047dcc2444e3.mp4

**Comment by Tfarcenim** [comment]
Curious, sure you don't have a vacuum or item magnet picking it up somewhere?  I can't reproduce this using only dank storage.

**Comment by Larsenist** [comment]
Turned out it was shooting out to the North every time so it was flying off
the map and I just didn't see it. lol

*Jonathan R. Larsen*
Synetic Technologies

*704.452.7736 Direct*
Contact@JRLarsen.net
