### ISSUE TITLE
Tool becomes unbreakable when locked in the first slot of a dank

### ISSUE THREAD

**Issue by olegok111** [Tfarcenim/Dank-Storage#127]
If the player puts a tool with 1 durability point in the first slot of a dank, locks it (Ctrl+click) and uses it, it'll look and sound like the tool was broken, but the tool will stay in a dank like nothing happened.

https://user-images.githubusercontent.com/25262677/126035355-8e4aa539-2c08-4b24-9718-072f97bc1a0a.mp4

**Comment by Tfarcenim** [comment]
Confirmed not possible

**Comment by Rowbotronics** [comment]
I was able to replicate this in 1.16.5 with Dank Storage 3.19 as the only installed mod. Locking a slot with a tool in it prevents it from being removed when it runs out of durability.  Instead the durability goes negative and plays breaking particles/sound every time it is used. When I tested with 3.21 the durability of the tool just doesn't decrease at all, regardless of whether or not the slot is locked.
