### ISSUE TITLE
using a stacked buckets while dank in inventory crashes client

### ISSUE THREAD

**Issue by minecrafterseppe** [Tfarcenim/Dank-Storage#131]
using stacked buckets for example on a fluid tank any type
crashes your client
modpack : AOF4
version of modpack : 0.0.8
fabric  1.17.1
[crash-2021-07-30_09.47.12-client.txt](https://github.com/Tfarcenim/Dank-Storage/files/6905902/crash-2021-07-30_09.47.12-client.txt)

**Comment by Tfarcenim** [comment]
No fabric in the forge repo
