### ISSUE TITLE
Placing a dank in a dock and retrieving it does not preserve pick up settings

### ISSUE THREAD

**Issue by tye425** [Tfarcenim/Dank-Storage#133]
It just gets reset to the default. It would be nice if it kept it's pickup attributes.

**Comment by gary-conlon** [comment]
If possible also if the dank is set to void when placed into the dock can it void any extra items inserted into the dock. 

Also noted latest version 1.16.5 when the dank is placed in a dock the pickup settings are not held.

**Comment by Tfarcenim** [comment]
This has been fixed on the fabric branch, Forge will get it once it's on 1.18.
