### ISSUE TITLE
Can't change to construction mode 1.16.5

### ISSUE THREAD

**Issue by Rawgreen** [Tfarcenim/Dank-Storage#134]
I can't change danks modes not only for dank 3 i tried others and still same issiue

![dank](https://user-images.githubusercontent.com/59456551/132095988-5fdbbabb-2e8f-44b0-8bca-87193e9f5fb4.png)
![dank2](https://user-images.githubusercontent.com/59456551/132095990-41b04275-b0d0-45f5-9301-0febf58b070d.png)
![dank3](https://user-images.githubusercontent.com/59456551/132095991-4f473f15-168b-46d2-a277-44152ab86cba.png)

**Comment by Tfarcenim** [comment]
Doesn't currently work with mouse buttons

**Comment by Tfarcenim** [comment]
this is outdated
