### ISSUE TITLE
Mob Duplication with Industrial Foregoing and Occultism

### ISSUE THREAD

**Issue by MuteTiefling** [Tfarcenim/Dank-Storage#135]
Mod versions:
dank storage: dankstorage-3.16
occultism: occultism-1.16.5-1.10.2
industrial foregoing: industrial-foregoing-1.16.5-3.2.14.6-14

forge: 36.2.2

Steps to reproduce

1. Place a bunch of (IF) Mob Imprisonment Tools or (Occ) Soul Gems in a Dank
2. Set the Dank to Construction mode
3. Right click a mob

All of the Mob Imprisonment Tools or Soul Gems will now be filled with the mob, effectively instantly duplicating it for no cost.

**Comment by Tfarcenim** [comment]
hmm, I wonder if it still occurs if say CT was used to adjust stacksize... for now though adding to `dankstorage:blacklisted_usage` should suffice
