### ISSUE TITLE
[Fabric 1.17.1] Crash when attempting to use an empty dank in construction mode

### ISSUE THREAD

**Issue by Gerdathlete** [Tfarcenim/Dank-Storage#137]
I'm using Dank Storage Fabric Version 2.1-1.17.1 through the All of Fabric 4 modpack.

When I make a new dank and switch to construction mode, then right click as if I were to place a block, the game crashes instantly.
Crash report: https://pastebin.com/KdVUnrha

**Comment by Tfarcenim** [comment]
No fabric posts on the forge repo

**Comment by Gerdathlete** [comment]
Where should I report issues with the Fabric version of Danks. I haven't found a github repo or a discord for the fabric version.

Edit -
Nevermind, just had to search for it on your profile. You might get better feedback if its linked on the CurseForge page.
