### ISSUE TITLE
Lost all dank items 

### ISSUE THREAD

**Issue by serj1980** [Tfarcenim/Dank-Storage#138]
Fabric 1,17,1 (all of fabric mod pack)
1. Items loaded from moden indastial pipe to docked dank storage.
issue 1: dank group items by 64 (dank redstone level)
issue 2: by pressing Sort button (dank storage button, not another mod sort) world is completed crashed (negative value error in stack trace)
2. Get automatically created backup (full copy of related world in saves folder, tested on several backups)
issue 3: dank in handle is empty
issue 4: all docked danks not allow to open it, if extract dank from dock and open it by hand is empty.

**Comment by Tfarcenim** [comment]
Incorrect repo
