### ISSUE TITLE
[Suggestion] Removing a Dank from the Dock should insert it directly into your inventory, instead of throwing it in a random direction

### ISSUE THREAD

**Issue by aaronhowser1** [Tfarcenim/Dank-Storage#143]
![image](https://user-images.githubusercontent.com/15698722/141384222-65f98d85-2020-4748-beca-4ef6bf9081af.png)

The problem *might* be that the item drop spawns in the center of the block, instead of outside somewhere? Maybe? Idk. Even then, it shouldn't ever be an item drop imo, unless your inventory is full.

**Comment by djmattyg007** [comment]
I just lost a dank with a lot of items because I accidentally right-clicked a different dank into a dock. I'm playing a skyblock world, so it just flew off into the void :(

**Comment by Tfarcenim** [comment]
implemented
