### ISSUE TITLE
Adjusting screen position of Dank HUD element does not move state tooltip

### ISSUE THREAD

**Issue by ClintonOrdonez** [Tfarcenim/Dank-Storage#144]
When using the config to adjust the Dank HUD element position, the tooltip that states whether the dank is in "bag" or "construction" mode does not relocate with the item preview. Having anything in the offhand causes overlap with the default position.

Default HUD config:
![2021-11-24_18 53 51](https://user-images.githubusercontent.com/43009957/143364460-fc827a0d-564d-4496-9429-a45a37368c2b.png)

Changing the Y position to -50:
![2021-11-24_18 54 16](https://user-images.githubusercontent.com/43009957/143364490-fcc82c65-d3c7-4120-9e48-484aff8b8914.png)

**Comment by Tfarcenim** [comment]
Fixed in 1.18+
