### ISSUE TITLE
Dropping items from a dank forces them to stack in stack sizes of 64

### ISSUE THREAD

**Issue by CILet99** [Tfarcenim/Dank-Storage#145]
When you drop something out of a dank and pick up the items they stack to 64 even if the items can only stack to 1 item. If you use this correctly you can duplicate any items. 
First put a bunch of empty danks into another dank. Then throw them out to get a stack of danks. When you put items into the stack of danks it gets put into every dank in the stack, so when you unstack them you get a duplication of every item in the danks for each dank in the stack.

**Comment by Tfarcenim** [comment]
> ... Then throw them out to get a stack of danks. ...

This is the part I can't reproduce, how are you able to remove unstackables as a stack?

**Comment by Tfarcenim** [comment]
I'll take it as not possible then
