### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by castilio20** [Tfarcenim/Dank-Storage#149]
if you have the the dank in your inventory you cant use the squeezer from integrated dynamics
squeezer works with right click to put the log in it but if you have the dank in your storage it doesnt let you

**Comment by Tfarcenim** [comment]
This is no longer an issue in 3.19

**Comment by radiomike** [comment]
This still seems to be an issue. 

Tested in ATM6 1.8.19 with dank storage version 3.19 and Integrated dynamics versions 1.10.6.  
Also tested in world with just ID and dank mods and dependencies. Versions 3.20 and 1.10.7

If the null is in your inventory and set to any of the pickup modes, then you can't right click an item into the integrated dynamics squeezer or drying basin.
If the null isn't set to pick up, then it will insert.

**Comment by Tfarcenim** [comment]
> If the null is in your inventory and set to any of the pickup modes, then you can't right click an item into the integrated dynamics squeezer or drying basin.

Could've said this 3 months ago, I'm not going to be in a hurry to fix this one because it's not fatal and I have more pressing matters.
