### ISSUE TITLE
Crash when crafting null

### ISSUE THREAD

**Issue by Ravalli03** [Tfarcenim/Dank-Storage#15]
When using JEI to upgrade a donk, the game crashes. If I place the items in a crafting grid not using JEI, game doesn't crash.

Minecraft; 1.12.2
Forge 14.23.5.2838
Donk; 1.12.2-1.4pre11

It did not create a crash report the 2 times it has happen.

**Comment by Tfarcenim** [comment]
any logs? latest or debug
