### ISSUE TITLE
Various suggested improvements

### ISSUE THREAD

**Issue by SamayaNL** [Tfarcenim/Dank-Storage#150]
1. **Add option to prevent the dock from emptying slots**. Usecase is when you use a dank for general storage, but also for storage of building blocks or health potions, and you do want to empty the general storage slots when put into a dock, but keep your building blocks and other useful items in the dank. 
2. **Prevent the dock from resetting dank pickup settings** (all, filtered etc)
3. **Make it so that shift clicking locked dank slots. Doesn't remove the every last item, but keep one in the slot.** 
4. **Add a preview window when hovering over dank**

**Comment by Tfarcenim** [comment]
> 1. Add option to prevent the dock from emptying slots. Usecase is when you use a dank for general storage, but also for storage of building blocks or health potions, and you do want to empty the general storage slots when put into a dock, but keep your building blocks and other useful items in the dank.

Use a second dank, docks are designed strictly for item transferring and interfacing

2. is a thing on 1.18 now, 3 is a disaster I'm not touching yet, and 4 is implemented in dev for 1.18
