### ISSUE TITLE
1.18 porting effort

### ISSUE THREAD

**Issue by madkat** [Tfarcenim/Dank-Storage#156]
Let me just start with: I really appreciate your work on this mod. It's such a QoL boost when mining and it is a big staple in my group in any modded MC game. Playing ATM7 on 1.18.1 without Dank Storage is awful!

I started getting an environment setup this week to help with the porting effort. After reading some other issues, it sounds like you are in the midst of another significant code change. Is that for changing over to the official mappings or something else?

If you have a work-in-progress branch, I'd be happy to chip in some time on whatever is outstanding.

**Comment by Tfarcenim** [comment]
Don't port this version, the mod's been rewritten (again) for 1.18+, look here if you want to help although I'm not releasing any builds until 39.1.0+

https://github.com/Tfarcenim/DankStorageFabric

**Comment by Tfarcenim** [comment]
The names are already in mojang so all that really needs to be done is converting the fabric api stuff into the forge equivalent, I'm preoccupied with other matters at this moment, otherwise I would do it myself.

**Comment by madkat** [comment]
Made some progress over the weekend retargeting the DankStorageFabric 1.18.x branch to forge. It is going to take some experimentation on my end to understand some of the differences.

Will this work eventually go into DankStorageFabric or Dank-Storage? I could do a 1.18.x-forge branch on the former, or just a 1.18.x branch on the latter.

**Comment by Tfarcenim** [comment]
I made a 1.18 branch here for you to PR against.

**Comment by madkat** [comment]
Great, thanks!

**Comment by Tfarcenim** [comment]
this is no longer needed
