### ISSUE TITLE
Mahou Tsukai's Durability Exchange Blood Circle is deleting items from an equipped Dank

### ISSUE THREAD

**Issue by stepsword** [Tfarcenim/Dank-Storage#157]
Hi, 

I'm the Mahou Dev, someone sent me this issue:

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/633

I believe it is caused by ItemStackMixin in Dank Storage, which runs on the "caster's" held item regardless of which item is being broken.

I suspect a similar interaction could occur whenever a mod tries to use durability from an item not held in the person's main hand.

**Comment by Tfarcenim** [comment]
The left click abilities are a bit jank anyways, might as well remove them.
