### ISSUE TITLE
Sorting a dank with multiple oversized stacks reduces one of the stacks to 64 items

### ISSUE THREAD

**Issue by yorii** [Tfarcenim/Dank-Storage#158]
Using:
InventorySorter-1.8.4-1.18
dankstorage-1.18.1-3.5.4

To reproduce:
Fill a dank with two stacks of the same item, where both stacks have more than 64 items.
Press the autosort button.
One stack will retain its original size, the other stack will be reduced to 64 items.

**Comment by yorii** [comment]
Duplicate issue posted to inventory sorter github: https://github.com/kyrptonaught/Inventory-Sorter/issues/73

**Comment by Tfarcenim** [comment]
Not my fault, I don't support 3rd party sorters because they never handle large stack sizes correctly.
