### ISSUE TITLE
Auto-Pickup keybind doesn't seem to function in multiplayer

### ISSUE THREAD

**Issue by katubug** [Tfarcenim/Dank-Storage#16]
* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2846-universal
* **Modpack version** (links to current modlist): [1.7.1](http://enthusiasticraft.cf/modpack-update-1-7-1/#modlist)
* **Mod versions:** dankstorage-1.12.2-1.4-pre11

I tested everything in singleplayer and didn't have any issues getting the danks to pick things up, but myself and another player on my multiplayer server have been unable to get them to change mode via the hotkey. I've double checked that the key isn't overriding anything. It just doesn't seem to be responding.

Thanks for your time, let me know if there's anything I can do to help!

**Comment by niftybottle** [comment]
Same here. There's an error in the logs, I'll try to grab it next time the server stops.

**Comment by Tfarcenim** [comment]
1.12 is unsupported, find a different mod
