### ISSUE TITLE
Dank Storage ID Change

### ISSUE THREAD

**Issue by Mi6kbuttface** [Tfarcenim/Dank-Storage#169]
I recently changed one of my worlds because of a chunk error so in order to save my stuff and progress, I put all my inv and stuff into a dank and then ported the dank storage info to the next world. When I got to the next world the danks ID were changed so I cant access my stuff, I was wondering if there is any way I can access or change a danks id, either with a /give command or something.

**Comment by Tfarcenim** [comment]
Wrong repository, also, yes there is commands to change it.
