### ISSUE TITLE
Issue with inventorysorter

### ISSUE THREAD

**Issue by cacione** [Tfarcenim/Dank-Storage#17]
1.14.4 / 1.4a 
When sorting with inventorysorter-1.14-16.0.0 (cpw) any stack bigger than 64 gets split. With items overflowing the capacity of the dankstorage getting deleted.
Not sure if this is an donkstorage issue or inventorysorter but perhaps the items that overflow the capacity could be dropped instead of destroyed.

**Comment by Tfarcenim** [comment]
it will not work with most sorting mods because they assume a stack can't be any bigger than 64 which will naturally break things.
To compensate for this, I will be adding a sort button.

**Comment by Tfarcenim** [comment]
ah ha, you're going to want to blacklist it https://github.com/cpw/inventorysorter/blob/master/src/main/java/cpw/mods/inventorysorter/Config.java

**Comment by cacione** [comment]
This can be closed now since removing inventorysorter solved it and version 1.5 has a sort option.
