### ISSUE TITLE
(1.18.2) hotkeys not working.

### ISSUE THREAD

**Issue by AekaF** [Tfarcenim/Dank-Storage#174]
Hello, just installed Dank Storage for 1.18.2 direwolf20 pack. Although all the hotkey conflicts were resolved, hotkeys still do not work. Right now it is only possible to use in bag mode. Wanted to let you know!

**Comment by TheAngryFire** [comment]
Same issue here but on ATM7 Hotkeys are not working...

**Comment by Ackmard** [comment]
Yeah same, they don't even work with just this mod installed.

**Comment by coaber** [comment]
same here. using latest version of Dank along with FML 40.1.84.

**Comment by Tfarcenim** [comment]
4.0.2 (5.0.2 for 1.19 users) fixes this
