### ISSUE TITLE
(1.18.2) Unable to extract anything from a dock with any mod's item interaction

### ISSUE THREAD

**Issue by Malkierian** [Tfarcenim/Dank-Storage#176]
I'm in the All the Mods 7 Sky pack. Although I'm not sure how that could interfere, I know it's possible. I'm hoping at the least I can get some help tracking down the issue if it is on my end.

Anyway, I've tried hooking it up directly to a Refined Storage network with an importer and an external storage interface, as well as trying to hook Pipez' item pipe and Mekanism's logistical transporter, and nothing has shown to be able to interact with a dank's storage, on any side of the dock.

**Comment by Tfarcenim** [comment]
confirmed, it needs an iitemhandler capability attached

**Comment by Malkierian** [comment]
For some reason, RS importers still can't access. Tested with 4.1. External Storages can, though.
