### ISSUE TITLE
[1.19.2-5.1] Upon upgrading a Dank 1 to Dank 2, items inside are voided

### ISSUE THREAD

**Issue by Gronglegrowth** [Tfarcenim/Dank-Storage#178]
Using Forge 43.1.47.

When crafting the recipe for the Dank 2, with the Dank 1 having items in it, the result looks like it'll have the same items in, but once you craft it and open it up, the items in are voided. This happens with only Dank Storage loaded, at first I had thought it was one of my inventory or crafting tweaks mods messing with it, but I loaded it alone to confirm.

**Comment by Malkierian** [comment]
I feel like this is probably related to what I was just noticing, but when breaking a dock with a dank inside, this also voids the items inside. This was on 1.18.2-4.1, though.

**Comment by Tfarcenim** [comment]
> I feel like this is probably related to what I was just noticing, but when breaking a dock with a dank inside, this also voids the items inside. This was on 1.18.2-4.1, though.


The items aren't actually gone, but a command may need to be used to set the frequency back

In the other case, the items are actually gone

**Comment by Malkierian** [comment]
How is that completed? Would seem to me that it should maintain items across upgrades, and should keep the channel when the dock is broken (or vice versa, I couldn't tell which you were addressing with each comment).

**Comment by Tfarcenim** [comment]
Both

**Comment by Gronglegrowth** [comment]
Commits were made to both 1.18 and 1.19 branches which I assume have fixed both of these problems, just before this was marked as closed.

**Comment by Malkierian** [comment]
Oh, I see. The closing comment made it seem like we just had to deal with it period. I wasn't worried about the stuff I lost before the bug was reported XD
