### ISSUE TITLE
Compression deletes items

### ISSUE THREAD

**Issue by duckslayr** [Tfarcenim/Dank-Storage#179]
When toggling the compression button while the dank is full, it deleted a lot of items (almost a stack of diamonds included).

**Comment by duckslayr** [comment]
ATM8 1.0.0

**Comment by Tfarcenim** [comment]
Do you have any logs I could look at?

**Comment by duckslayr** [comment]
There wasn't anything in the server console output, but I'll see if I can get at the logs later tonight.

**Comment by Tfarcenim** [comment]
fixed
