### ISSUE TITLE
dank deletes items 

### ISSUE THREAD

**Issue by IamSweetie** [Tfarcenim/Dank-Storage#184]
dankstorage-1.19.2-5.1.2
dank 2 with all slots used will replace all items in all the slots with a stack of a single item if used with mouse tweaks middle click sort option (e.g. if you middle click on a slot containing cobblestone, all items in all slots will be replaced by 1 stack of cobble)

**Comment by Tfarcenim** [comment]
Mousetweaks bug, nothing I can do on my end.

**Comment by koalalord9999** [comment]
Can confirm. I was so mad when I accidentaly sorted and it deleted EVERYTHING :CC

**Comment by YaLTeR** [comment]
Mouse Tweaks does not have sorting functionality. It's some other mod.

**Comment by LuciusV** [comment]
I confirm. SimpleInventorySorter deleted a lot of my items accidently. Its extremely frustrating. Is this possible for you to forbid other inventory sorting mods from touching Dank inventory?

**Comment by Tfarcenim** [comment]
I've banned quark in the past for incorrectly implemented item sorting, I don't have the time to prevent every mod from touching the slots.
