### ISSUE TITLE
1.19 Switch usetype broken

### ISSUE THREAD

**Issue by Crimix** [Tfarcenim/Dank-Storage#186]
After playing with it for some time on a server with a lightly modified Direwolf20 1.19.2 pack.
The switch usetype key breaks and does not register a press, thus it is impossible to switch it from construction -> bag or bag -> construction.

Minecraft version: 1.19.2
Forge version : 43.1.57

**Comment by Tfarcenim** [comment]
Cannot reproduce, are you sure it isn't conflicting with another mod and is it changed from default?
