### ISSUE TITLE
Client crash 1.19.2

### ISSUE THREAD

**Issue by Realever** [Tfarcenim/Dank-Storage#191]
hi,
i updated your mod to the current version 1.19.2-5.1.4 and since then my client crash on the server when i´m with the mouse over or near the the dankstore am.I downgrade to the version 1.19.2-5.1.3 and there i don´t have this crash/error.Here is the crash log: https://pastebin.com/0tF3iac2
Minecraft version: 1.19.2
Forge: 43.2.3
dankstorage: 1.19.2-5.1.4

**Comment by ApoIIy0n** [comment]
same issue here nullpointerexception in new dank version 5.1.4

https://mclo.gs/yz8jE7r

**Comment by Tfarcenim** [comment]
Of course mods are calling capabilities on the clientside
