### ISSUE TITLE
Crashing when mousing over Dank 1 in my inventory.

### ISSUE THREAD

**Issue by GGearZZ** [Tfarcenim/Dank-Storage#194]
Good Day. I'm currently playing All The Mods 8 v1.0.9 on a server with a friend. Both of us crash when mousing over Dank 1 in our inventories. See the attached log.
[crash-2023-01-27_21.08.04-client.txt](https://github.com/Tfarcenim/Dank-Storage/files/10524377/crash-2023-01-27_21.08.04-client.txt)

**Comment by Tfarcenim** [comment]
5.1.5 has this fixed already

**Comment by Tfarcenim** [comment]
Tell the pack creators to update

**Comment by GGearZZ** [comment]
Thank You!
