### ISSUE TITLE
Fetaure request: Display item name in construction mode?

### ISSUE THREAD

**Issue by MissPotato** [Tfarcenim/Dank-Storage#196]
When in construction mode the current behavior is to just show the icon of the object that is selected. While the preview is useful, items with similar or identical visuals are very hard to tell apart.  When sneak + scrolling to select the slot it would be very useful to have the actual name displayed. Sort of like when you select an item on your hortbar normally a toast is displayed with  the item's name. Vazkii's Morph-O-Tool does this as an example.

A use case is I have a few Inmis backpacks I renamed to the mods that I am using them with, one name botania and one named create. Both of these backpacks are the same color. (Yes, I know nesting backpacks is a dangerous game.)

**Comment by Tfarcenim** [comment]
Added in 5.1.6

**Comment by MissPotato** [comment]
Agh, sorry, I hadn't even thought to check if there were newer versions, the one in the pack is super out of date, thank you!
