### ISSUE TITLE
Suggestion: Texture change maybe? 

### ISSUE THREAD

**Issue by NomSTeh** [Tfarcenim/Dank-Storage#2]
First Texture
![dank_1](https://user-images.githubusercontent.com/52329098/63193341-92222880-c0b0-11e9-9162-9cd0668d5dda.png)
Second Texture
![dank_2](https://user-images.githubusercontent.com/52329098/63193363-a23a0800-c0b0-11e9-9d15-6bbb839e17d9.png)
Third Texture
![dank_3](https://user-images.githubusercontent.com/52329098/63193371-a8c87f80-c0b0-11e9-876b-6b1b4667ec4f.png)
Fourth Texture
![dank_4](https://user-images.githubusercontent.com/52329098/63193388-b120ba80-c0b0-11e9-89f2-b367c05000b9.png)
Fifth Texture
![dank_5](https://user-images.githubusercontent.com/52329098/63193405-bb42b900-c0b0-11e9-9b80-adbe6db8a12d.png)
Sixth Texture
![dank_6](https://user-images.githubusercontent.com/52329098/63193411-c1d13080-c0b0-11e9-8fc8-ddc33acdade0.png)
Seventh Texture
![dank_7](https://user-images.githubusercontent.com/52329098/63193437-d01f4c80-c0b0-11e9-947d-67365fcd14d7.png)

I'm making some alternatives following more of the rainbow style you were initially going for. This current style i made is to make it show whats actually changing and how in the process of upgrading the dank storage.

**Comment by NomSTeh** [comment]
Rainbow Version: 

Dank 1 Texture
![dank_1](https://user-images.githubusercontent.com/52329098/63194788-42456080-c0b4-11e9-9eab-b3160359e32e.png)
Dank 2 Texture
![dank_2](https://user-images.githubusercontent.com/52329098/63194796-4a050500-c0b4-11e9-96ce-e43f680b1ac7.png)
Dank 3 Texture
![dank_3](https://user-images.githubusercontent.com/52329098/63194847-63a64c80-c0b4-11e9-80e2-7597907e3f55.png)
Dank 4 Texture
![dank_4](https://user-images.githubusercontent.com/52329098/63194857-6d2fb480-c0b4-11e9-950a-aaee3f0e85e2.png)
Dank 5 Texture
![dank_5](https://user-images.githubusercontent.com/52329098/63194867-73be2c00-c0b4-11e9-84f1-15ee6388ac0b.png)
Dank 6 Texture
![dank_6](https://user-images.githubusercontent.com/52329098/63194877-7a4ca380-c0b4-11e9-873b-f9b22a8d1f96.png)
Dank 7 Texture
![dank_7](https://user-images.githubusercontent.com/52329098/63194884-80db1b00-c0b4-11e9-8071-87fd6a81210e.png)

**Comment by Tfarcenim** [comment]
that is brilliant, I was actually working on the models for them, but ran out of time so I had to push a build before the weekend hit

**Comment by Tfarcenim** [comment]
getting new mods approved on weekends sucks

**Comment by Tfarcenim** [comment]
and it's in
