### ISSUE TITLE
Suggestion: Shift clicking Compress to compress all non-reversable blocks. And adding CTRL click to toggle this. CTRL+SHIFT to toggle non-reversables

### ISSUE THREAD

**Issue by koalalord9999** [Tfarcenim/Dank-Storage#200]
This would be super helpful for modpacks using garden of glass, or other similar features. Allowing you to compress the 4 pebbles into a cobble stone.

**Comment by Tfarcenim** [comment]
While it's a nice suggestion, I won't be adding it because it's too easy to fatfinger nether warts for example.
