### ISSUE TITLE
Dank SELF-DESTRUCTS When Using Last of AE Cable

### ISSUE THREAD

**Issue by Quest79** [Tfarcenim/Dank-Storage#201]
Im playing ATM8
MC 1.19.2
[dankstorage-1.19.2-5.1.6.jar](https://www.curseforge.com/minecraft/mc-mods/dank-storage/files/4395369)

- I had a fully upgraded dank. I put popes from various mods in it. The pipe i was using was a dense fluix cable from AE. 
- All slots with items in them were locked. 
- Upon using the last (above) cable in my dank, the entire dank item simply vanished. This is the second time this has happened. 
- It has been a few days multiple restarts and it is nowhere. It is just gone. 

I feel like this is a major issue.

**Comment by Quest79** [comment]
I just did a test and this is easy to repeat. Added 2 cables to dank, used both, dank self-destructs upon use of second cable. Its almost funny. ... Almost

I tried with pipz mod and it doesn't do this. Tried again with AE export/import bus and it self-destructs again.

**Comment by Tfarcenim** [comment]
great, another item for the blacklist

**Comment by Tfarcenim** [comment]
Add the items to the use blacklist
