### ISSUE TITLE
1.19.2 Docked Dank hooked up as external storage for Refined Storage accepts all items.

### ISSUE THREAD

**Issue by hairlessOrphan** [Tfarcenim/Dank-Storage#205]
Playing in ATM8.

I have a Dank 6 set to Yellow pickup mode (only pickup items that are already in the Dank). When it's docked and hooked up as a Refined Storage External Storage, any item dropped into the Refined Storage system will get stuffed into a free Dank slot, ignoring the Yellow pickup mode setting.

I think the expected behavior is that the Dank should operate according to its pickup mode. When Gray, it should not accept any items routed in through any means. When Yellow, it should only accept items already in the Dank. Etc...

**Comment by postal291** [comment]
workaround is to partition the storage bus for the dank's contents.  it'll still over fill or over pull, but at least it'll be the right items.

**Comment by Tfarcenim** [comment]
Working as intended, the pickup modes to nothing while docked, use slot locking to configure
