### ISSUE TITLE
1.20.1 Update request

### ISSUE THREAD

**Issue by Zorro8183** [Tfarcenim/Dank-Storage#207]
is this going to be updated to 1.20.1?

**Comment by PokeMaserJ** [comment]
What do you know, already is https://www.curseforge.com/minecraft/mc-mods/functional-armor-trim/files/4606637

**Comment by Zorro8183** [comment]
that link you gave me is for armour or is Dank Storage included in that armor mod? we would like to use Dank Storage in 1.20.1 but as far as curse forge lists is only available for 1.19.2 or 1.19.4 but no 1.20.1

**Comment by PokeMaserJ** [comment]
my bad lol. For some reason I thought this was the GitHub for Functional Armor Trim

**Comment by EliteScouter** [comment]
Hopefully this gets updated to 1.20 so ATM9 can add it to the pack.

**Comment by Tfarcenim** [comment]
there is port
