### ISSUE TITLE
[1.20.1] Dank Storage is not showing up in JEI.

### ISSUE THREAD

**Issue by Gbergz** [Tfarcenim/Dank-Storage#209]
Title ^

Screenshot: 
![bild](https://github.com/Tfarcenim/Dank-Storage/assets/26634554/c8bcfb8d-961c-44f0-aa73-b26028d4d675)

MC: 1.20.1
Forge: 47.1.0
Dank Storage: 1.20.1-1

**Comment by Tfarcenim** [comment]
Forgot a creative tab, fixed
