### ISSUE TITLE
UI Disappears when items go into Storage while in hand.

### ISSUE THREAD

**Issue by FuuNoKamiOka** [Tfarcenim/Dank-Storage#21]
I noticed it recently that whenever items go into the Null, my UI disappears. I don't know if it's conflicting with "Mine And Slash" or not but this didn't use to happen.

No items:
https://i.gyazo.com/0b201229995f560a05d8b8be926089a2.png

With items:
https://i.gyazo.com/d53e734a61847c239932149ee4525a16.png

EDIT: I have done some tinkering and found that the preview config option being turned off fixes this issue. Figured I'd edit this in case anyone else has this issue.

**Comment by Tfarcenim** [comment]
that's annoying, wonder what's causing it since it's not happening in the modpack I'm playing adventures of halk.

**Comment by FuuNoKamiOka** [comment]
I don't know. I'm using a mod called "Mine and Slash" that adds more bars to the side. Once I got rid of the preview in the Dank config the UI disappearing stopped.

**Comment by Tfarcenim** [comment]
full modlist? because I'm using Mine and Slash as well and it's not vanishing

**Comment by FuuNoKamiOka** [comment]
Advanced Rotten Flesh to Leather
Angel Ring
AppleSkin	
Biomes O' Plenty	
Building Gadgets	
Coal Chunks	
Corail Woodcutter	
Curios API	
Cursed Earth	
Cyclops Core	
Dank Storage	
Dungeon Crawl	
EverlastingAbilities	
Extra Bows	
Fast Leaf Decay
GemsPlusPlus		
Gobber [FORGE]	
Hwyla		
Inventory Sorter	
Iron Chests	
Just Another Rotten Flesh to Leather Mod	
Just Enough Items (JEI)	
Light Level Overlay Reloaded	
Linked Destruction	
MCFurnace	
Mine and Slash		
MoreOres Mod	
Mouse Tweaks	
Placebo		
Ring of Attraction [FORGE]		
Ruins (Structure Spawning System)	
Scalable Cat's Force		
Silent Lib	
Simple Farming		
SimpleHarvest		
Speedy Hoppers	
Storage Drawers		
Torcherino	
Treasure Bags	
U Team Core		
Useful Backpacks		
Vanilla+ Tools		
VoxelMap

**Comment by Tfarcenim** [comment]
Not disappearing in adventures of halk so mod bug likely

**Comment by Tfarcenim** [comment]
doesn't seem to be an issue in modern versions
