### ISSUE TITLE
1.18.2 Lagy

### ISSUE THREAD

**Issue by G4ming69** [Tfarcenim/Dank-Storage#213]
1.18.2, unfortunately very lagy when I place blocks.
modpack Vault hunters 3.10.1 (yes, I know that thanks isn't actually in the pack) but the mod is a must have <3
Forge 40.2.1

**Comment by Tfarcenim** [comment]
You added a mod to a prebuilt modpack and are complaining about it being laggy when it has nothing to do with the mod.
