### ISSUE TITLE
[Feature Request] Middle click to pick block

### ISSUE THREAD

**Issue by batuozdemir** [Tfarcenim/Dank-Storage#214]
I think it would be a great idea to use the "pick block" key (usually middle mouse) to select the block if it's present in Dank storage. This would make building with Dank a lot faster. 

Also, a key or some way (like shift+right click) to open the dank storage in construction mode would be nice.

Thanks!

**Comment by Tfarcenim** [comment]
This is already possible in forge/fabric 1.20.1, if there's another version it's missing on make a new issue.
