### ISSUE TITLE
Compresses reversible 3x3 and 2x2 recipes

### ISSUE THREAD

**Issue by DarkMarauders** [Tfarcenim/Dank-Storage#215]
![image](https://github.com/Tfarcenim/Dank-Storage/assets/47243203/d9980059-92e3-428c-8c3b-18fcaed80c9e)
I accidentally clicked this button, and now all the minerals have turned into blocks. I don't know how to get it back.

**Comment by Tfarcenim** [comment]
With a crafting table, this is functioning as intended.
