### ISSUE TITLE
Dank Storage crash with ae2 storage bus 

### ISSUE THREAD

**Issue by Turtle1506** [Tfarcenim/Dank-Storage#216]
https://[api.mclo.gs/1/raw/ZkSMZpf](https://api.mclo.gs/1/raw/ZkSMZpf)
[crash-2023-09-01_13.19.46-server.txt](https://github.com/Tfarcenim/Dank-Storage/files/12497521/crash-2023-09-01_13.19.46-server.txt)
[crash-2023-09-01_13.34.13-server.txt](https://github.com/Tfarcenim/Dank-Storage/files/12497522/crash-2023-09-01_13.34.13-server.txt)

**Comment by Tfarcenim** [comment]
reproduction steps?

**Comment by NotSwan** [comment]
I experienced this issue as well. ATM9 - 0.2.9 server.

On a server I host the bug occurred specifically on placing the Dank into a Dock connected to a RS external storage. The player stated that while crafting the danks from a Refined Storage system, they appeared to have stacked within his inventory. So he had a stack of 2 Danks that he noticed, and separated. He does not remember exactly, but is suspicious that of his 4 Danks the one he placed that crashed was the one that had stacked. I doubt it is a number of dank issue as I have a setup with 3 Dank7s connected via AE2 storage bus.

The crash was not fixed until the chunks had been deleted from the world, even with force loading of chunks disabled the crash persisted.

That is all the detail I was able to surmise from the player, I hope this can help give you a lead!

**Comment by phit** [comment]
> I assume It's because I accidently placed a dank in a Dock with -1 . Aka unconfigured.

to quote one of my players, sounds like that is the issue, i patched our server for now and put that valueOf in a try/catch with default value, you should probably block putting unconfigured danks into the dock..

**Comment by MWG-Logan** [comment]
We're seeing as well.
**Pack**: All The Mods 9
**Link**: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9
**Version**: 0.2.23

User:

> i had a stack of 3 final-tier danks in my hand. I had a dock already connected to my AE2 me system with a storage controller. The server crashed when I clicked the stack of 3 danks into the dock
storage interface*
the danks were newly crafted; no configuration was done to them

I told them to post here with as much detail as possible so you can attempt to replicate it.
Lmk if my logs from the server's end would be helpful here.

**Comment by ChrisG97** [comment]
> We're seeing as well. **Pack**: All The Mods 9 **Link**: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9 **Version**: 0.2.23
> 
> User:
> 
> > i had a stack of 3 final-tier danks in my hand. I had a dock already connected to my AE2 me system with a storage controller. The server crashed when I clicked the stack of 3 danks into the dock
> > storage interface*
> > the danks were newly crafted; no configuration was done to them
> 
> I told them to post here with as much detail as possible so you can attempt to replicate it. Lmk if my logs from the server's end would be helpful here.

That's basically the gist of it. I did go into a single-player game and the same thing happened. Stack of danks right-clicked into a dank dock that has an ae2 storage interface connected to it.

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1-5
