### ISSUE TITLE
Commands using Frequency ID not working - Version 1.20.1-1.1

### ISSUE THREAD

**Issue by Thunder-Nova** [Tfarcenim/Dank-Storage#219]
Did a blunder where I accidently change one of my main dank's ID while the ID was locked with the "/dankstorage reset_frequency" (so couldn't change it back). [possibly perhaps prevent change if it's locked]

So I did check on the command [ /dankstorage unlock 0 ] and it gives me:
dankstorage.command.unlock.invalid_id

I did noticed that even "/dankstorage clear <frequency ID>" for specific clear doesn't work as well. Since I made an empty tier 5 dank as I was panicking, but wanted to put a dank tier 1 at it's ID after I got it fixed.

- ***Temporally Fix for Single player & server admin***

Thankfully I was on single player when it happened and managed to find out how to retrieve it with F3+i from a dock 
(Just change the tier # to the tier of Dank and the last 0 to the frequency)

/setblock ~ ~ ~ dankstorage:dock[tier=5]{ForgeCaps:{},settings:{construction:0,"dankstorage:frequency":0}}

Currently using version - 1.20.1-1.1

**Comment by Tfarcenim** [comment]
I commented them out during the 1.20.1 port, they were never really meant to be permanent commands, but for data migration.  I'll look into adding them back

**Comment by Tfarcenim** [comment]
Added a feature
