### ISSUE TITLE
Stack Underflow and dank issues 

### ISSUE THREAD

**Issue by DaniUg** [Tfarcenim/Dank-Storage#22]
I have a small problem
The P and O settings to pick up or void picking up stuff doesn't work
when you plant it and use it like a chest there is no problem.
But when you have it on the hot bar and click p or o there is no change no matter which mode the dank is set in (construction bag or chest)
However if you use it as a chest it can store huge amounts as intended.
Also, when you circle throught the item in your hotbar and you pass the dank it always appears a text sayin "Stack Underflow"

Just in case it's relevant this are the other mods I'm using:
GamemodeOverhaul
AmbientSounds
BiomesOPlenty
ChanceCubes
ChickenDropFeathers
Corail_pillar
Corail_pillar_extension_biomesoplenty
creat-mc1.14.4
dankstorage 1.5-pre2
Driudcraft
EasySteel
Embelishcraft
EnchanmentDescriptions
engineersdecor
extrabows
Voxelmap
gravestones
Hwyla
instahouses
Jei
JRFTL+
justenoughbuttons
Lightoverlay
luckyores
PowderPower
prefab
Optifine U_F4 pre7
Randomthings
RingofAtraction
RingofBlink
RingofRepair
Ruins
simplefarming
StorageDrawers
Structurize
Supertools
Travellerboots
WallpaperCraft
Worldhandler

**Comment by Tfarcenim** [comment]
The stack underflow is an issue caused by optifine, also, there is no longer a keybind for cycling pickup modes as that's now handled in the gui.

**Comment by DaniUg** [comment]
didn't know that, since the instructions you have on the web talk about o and p I though I surely broke something. 
I'll keep tinkering to see if I can set it to that the items i pick up got directly into the dank.
Thanks for the quick response mate :)

**Comment by Tfarcenim** [comment]
updating the description and mod today

**Comment by Tfarcenim** [comment]
no longer an issue in modern versions
