### ISSUE TITLE
[Bug] Duplication glitch

### ISSUE THREAD

**Issue by MellowFellow221** [Tfarcenim/Dank-Storage#220]
Tested on AOF6

Using a bundle and a dank, you can easily duplicate infinite items.

You can stack bundles within a dank and using the stacked bundles when you grab an item it creates duplicated versions of those items.

E.G. If you put 4 empty bundles into the dank and gain a stack of bundles when you then collect something like diamonds into the 4 bundle stack it quadruples the diamonds causing a dupe glitch

**Comment by MellowFellow-sudo** [comment]
Forgot to label 💀

**Comment by Tfarcenim** [comment]
Fixed in 4.4
