### ISSUE TITLE
Dank destroys servers on 1.20.1 with refined storage and extra storage busses

### ISSUE THREAD

**Issue by bonesieboy** [Tfarcenim/Dank-Storage#223]
when u make a new dank and dont look in it first and put in in a dank dock connected to a refined storage bus/extra storage bus the server will constantly crash over and over.

**Comment by bonesieboy** [comment]
ok so i worked some things out and it is actually just the dock that brakes the game if u put a dank in it that hasn't been opened it breaks.

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1-5
