### ISSUE TITLE
Compression not working

### ISSUE THREAD

**Issue by Pipeline929** [Tfarcenim/Dank-Storage#224]
So, I apologize if this is mentioned somewhere or if there is something im missing. I have used this mod in the past and from what I remember I just needed to click the "C" button to compress blocks. But when i do that nothing happens except it shifts things around like it's sorting. I have installed the mod on a vanilla playthrough to test it with compressium and All The Ores. But even adding the default tag within the allowed conversion list for iron ingots "minecraft:iron_ingot", none of the danks will compress a stack of 64 into any amount of iron blocks. Any assistance would be appreciated and again, I apologize if this has been mentioned somewhere or I am overlooking something.

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1-5

**Comment by thedevbob005** [comment]
Version 1.20.1-8 bug still exists. Playing in ATM9Sky
