### ISSUE TITLE
1.20.1 Fabric Danks erase inventory when upgrading. 

### ISSUE THREAD

**Issue by GeniusLocEye** [Tfarcenim/Dank-Storage#225]
It's as it says above. Data isnt written properly when they upgrade.

**Comment by DaddyKami** [comment]
have had the same issue just today tried checking all ID's but 0-10 are all empty now

**Comment by Tfarcenim** [comment]
upgraded from what?  crafting table?  upgrade items?

**Comment by Tfarcenim** [comment]
I'm going to say this doesn't happen
