### ISSUE TITLE
dank frequency linked to players lost 

### ISSUE THREAD

**Issue by pyscho974** [Tfarcenim/Dank-Storage#226]
i updated my all the mods 9 server to latest update. 0.2.31 .. after doing this  other players on my server with dank storage was unable to open the inventory ..  messaged that you cant open a level 7 dank in a level 3.  im only player with a level 7 dank so somehow they trying to link into my system since the server was updated.. 

am i missing a file to copy over other then my world folder with an updated server? since this happened only after i updated my server files and copied over the entire world folder to the updated files.

happend once before when they created a new dank and it tried to link into mine after the last server update..  i used the command /dankstorage reset_frequency untill i found an empty frequency for them. it apparently started at zero and went 1 by 1 threw all the frequencies .. having 6 total on the server.

**Comment by Tfarcenim** [comment]
I added a way to change it without OP
