### ISSUE TITLE
ATM 9 Crash when locking multiple items in t1 dank.

### ISSUE THREAD

**Issue by Aryxon** [Tfarcenim/Dank-Storage#227]
I was in the mines playing on All the Mods 9 pack and I just learned the lock feature of the dank so I held down CTRL and ran over all my items in my dank in a wide swath, not pressing CTRL on them one at a time but holding CTRL and just swiping over all slots and then suddenly my game crashed. It's a modified atm9 but I just added a few more create mods so nothing that really should cause this issue, but it does say in the log that it is caused by Dank Storage.

[crash-2023-12-22_03.51.22-client.txt](https://github.com/Tfarcenim/Dank-Storage/files/13751275/crash-2023-12-22_03.51.22-client.txt)

![2023-12-22_04 08 14](https://github.com/Tfarcenim/Dank-Storage/assets/14962917/c23b499d-cd2d-4c1c-b773-f81a6f3a843d)

**Comment by Aryxon** [comment]
Found out that it's caused by either clicking too much on some of the buttons in the interface or simply locking a empty bit of the white part of the ui....and it's a fairly consistent annoying crash.

**Comment by jduece** [comment]
i have the same issue but i cannot lock anything if i press control while the dank is opened it crashes

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1-6
