### ISSUE TITLE
Sneak (shift) scroll broken 

### ISSUE THREAD

**Issue by cacione** [Tfarcenim/Dank-Storage#23]
Minecraft 1.14.4 and dankstorage 1.5
Sneak (shift) scroll doesn't work anymore, even when placing the storage block down.

Not quite an issue but could the green glow be limited to construction mode.

**Comment by Tfarcenim** [comment]
What do you expect to happen when sneak scroll is used and what actually happens

The green glow is from one of the pickup modes, I got sick of wondering which ones were picking up which items.

**Comment by cacione** [comment]
When sneak scrolling it should be possible to switch between items on the hotbar. Same as scrolling without sneaking.
