### ISSUE TITLE
1.20.1-6 Forge Dank storage contents shared between players on dedicated Server 

### ISSUE THREAD

**Issue by MythCracker** [Tfarcenim/Dank-Storage#233]
I had crafted a dank some time ago. When a friend joined a dedicated server I setup and started crafting danks, and upgrading them he found that they already had items inside and though it was normal. Due to events we somehow realized that the inventory for the danks became shared somehow. Shared to the point that he can put an item into his level 6 dank, and I was able to pull those items out of my level 6 dank, and both of us could see that happen in real time. Any new danks are also having this problem.

**Comment by MythCracker** [comment]
Okay, so, I've realized that this was an issue with the frequencies getting conflicted. I'm now trying to fix it with the commands, but I can't tell how the commands are supposed to work exactly. Is there any documentation on exactly what the commands are and what their inputs are? Right now, If I type "/dankstorage lock" it prompts me with <dankstorage:frequency>. What am I supposed to put here after lock? Just an integer of the frequency? Doing that for ID 0 gets an error saying invalid_id. I've also tried doing 000. Putting anything besides a number immediately shows as an error and says "Expected Integer". 
![2024-02-15_20 21 53](https://github.com/Tfarcenim/Dank-Storage/assets/57191796/a01abbfa-d5ed-44ce-8010-c3e300eee44f)
![2024-02-15_20 21 56](https://github.com/Tfarcenim/Dank-Storage/assets/57191796/19ef8f88-e4eb-4b24-bc8b-d003343f7492)
![2024-02-15_20 24 44](https://github.com/Tfarcenim/Dank-Storage/assets/57191796/fb8106f5-5b54-45be-8d52-11feead45791)

**Comment by MythCracker** [comment]
Okay, sorry, I figured out how the commands are supposed to work, using the frequency and tier number, but doing /dankstorage set_tier 2 4  to set frequency 2 to tier 4 tells me that the frequency does not exist. Is there something I'm still doing wrong here?

**Comment by Tfarcenim** [comment]
commands currently don't work in 1.20.1, they will be fixed when I have time but I would like to know how the channels got mixed up to begin with

**Comment by MythCracker** [comment]
> commands currently don't work in 1.20.1, they will be fixed when I have time but I would like to know how the channels got mixed up to begin with

Ahh I understand, alright then. And as far as how it happened, after all the back and forth research through different posts and thinking back on it, I'm realizing it might have originally been caused through user error on my part. I probably left the channel unlocked by mistake or something like that. 

The only thing is that we're still having trouble with is changing the frequency ID through the GUI, for some reason it just won't save the ID even though the frequency doesn't exist yet. Or does the frequency need to exist before you can assign it?

**Comment by Tfarcenim** [comment]
> does the frequency need to exist before you can assign it?

Yes, it does, the only way to assign a new frequency is to remove the old one, but then you lose access to the old one without commands or nbt editing if it's locked

**Comment by Tfarcenim** [comment]
I have implemented a way to more easily switch ids
