### ISSUE TITLE
[1.20.1-13] Each new game start ID assignment starts with ID 0

### ISSUE THREAD

**Issue by Garonne** [Tfarcenim/Dank-Storage#234]
First of all: Danks already assigned an ID work fine.

Whenever I open a new dank (ID: -1) after I restart my local minecraft game my danks are assigned IDs starting 0, 1, etc... Despite those IDs being already assigned to other danks. This leads to frequencies being involuntary upgraded to higher dank levels (if the new dank is of a higher tier than the original one).

Current possible solve: When a new ID needs to be assigned, I first take a Tier 1 dank and assign it to a "new" frequency (ID: 0)...
Use /dankstorage reset_frequency to reset it back to -1, and repeat, until the Tier 1 dank is assigned the current highest frequency (or the first new frequency). THEN I take the first new dank and assign it the new frequency to unlock a new frequency.

Possible improvements:
It would be nice if there was a posibility to "open" a dank with frequency -1 without assigning it a real frequency and be able to manually assign it a new frequency. Currently, it's not possible to assign danks to frequencies which are not yet "opened" by the above method. Being able to assign frequencies currently not used would be a great help. Being able to assign a frequency using a command would also help.

Being able to set the "next unused frequency" by command would also be tremendously useful.

My request:
[New Command] Set next free frequency X.
[New Command] ~~Assign Frequency X, Tier Y to current dank.~~ Unlocking frequency if needed. (if not already working)

Edit: Assigning Tier and Frequency to a dank is already possible via command Set_Tier. Will it unlock new frequencies?
Ok... No matter which frequency I try, set_tier replies: "frequency doesn't exist", even if I have a dank with said frequency in hand.

**Comment by Tfarcenim** [comment]
> Whenever I open a new dank (ID: -1) after I restart my local minecraft game my danks are assigned IDs starting 0, 1, etc... Despite those IDs being already assigned to other danks. This leads to frequencies being involuntary upgraded to higher dank levels (if the new dank is of a higher tier than the original one).

Weird, any reproduction steps?  I tried doing what you said and it assigns fine.

> It would be nice if there was a posibility to "open" a dank with frequency -1 without assigning it a real frequency and be able to manually assign it a new frequency.

Noted, I will add it as a feature

Commands are currently disabled as they were only meant for fixing worlds back in 1.18 - 1.19 and I would rather find a proper fix.

**Comment by Garonne** [comment]
> Weird, any reproduction steps? I tried doing what you said and it assigns fine.

Well... As posted reproduction is apparently quite easy... Play MineCraft (All The Forge 10), add DankStorage, assign some Danks, unload the game (Main Menu is enough), restart/reload game, assign additional Danks.
New Danks are assigned starting from ID 0 again, though they should not.

Maybe some Mod incompatibility, though I don't seem to be the only one affected...

Actually issue #233 and #226 seem to have the same issue... Same problem, when switching to [1.20.1-6] or [1.20.1-5]

Is there some easy way to dump a complete list of mods? If it's an incompatibility, maybe I and the other two people can narrow it down by comparing our mod lists?
I know, "All The Forge 10" already has a huge list of Mods... (I got 247 mods right now...)

Here we go:

[... - updated list in next post]

I'll try to eliminate some mods to reduce the list...

**Comment by Garonne** [comment]
Issue persists in a fresh install of "All The Mods 10" with no optional files only Dank Storage added... So one of these mods must cause the conflict (in case it's a mod conflict).

 - Absent By Design Mod(absentbydesign)@1.8.0
 - AE2WTLib(ae2wtlib)@15.2.2-forge
 - AeroBlender(aeroblender)@1.20.1-1.0.1-neoforge
 - Alex's Delight(alexsdelight)@1.5
 - Alex's Mobs(alexsmobs)@1.22.8
 - Amplified Nether(amplifiednether)@1.2.4
 - AppleSkin(appleskin)@2.5.1+mc1.20.1
 - Applied Energistics 2(ae2)@15.0.23
 - Architectury(architectury)@9.2.14
 - Bad Wither No Cookie Reloaded(bwncr)@3.17.0
 - Balm(balm)@7.2.2
 - Better Advancements(betteradvancements)@0.3.2.161
 - BHMenu(bhmenu)@2.4.1
 - Biomes O' Plenty(biomesoplenty)@18.0.0.592
 - Blood Magic(bloodmagic)@3.3.2-44
 - Blue Skies(blue_skies)@1.3.31
 - Bookshelf(bookshelf)@20.1.9
 - Caelus API(caelus)@3.1.0+1.20
 - Catalogue(catalogue)@1.8.0
 - CC: Tweaked(computercraft)@1.109.6
 - ChoiceTheorem's Overhauled Village(ctov)@3.4.2
 - Citadel(citadel)@2.5.4
 - Cloth Config v10 API(cloth_config)@11.1.118
 - Clumps(clumps)@12.0.0.3
 - CoFH Core(cofh_core)@11.0.0
 - Collective(collective)@7.40
 - Comforts(comforts)@6.3.5+1.20.1
 - Compressium(compressium)@3.0.2-build.12+mc1.20
 - Config API(configapi)@1.20-2.2.1
 - Construction Wand(constructionwand)@1.20.1-2.11
 - Continents(continents)@1.1.4
 - Controlling(controlling)@12.0.2
 - CookingForBlockheads(cookingforblockheads)@16.0.3
 - CosmeticArmorReworked(cosmeticarmorreworked)@1.20.1-v1a
 - CraftTweaker(crafttweaker)@14.0.36
 - CraterLib(craterlib)@1.1.1
 - Create Diesel Generators(createdieselgenerators)@1.20.1-1.2h
 - Create Slice & Dice(sliceanddice)@3.2.0
 - Create(create)@0.5.1.f
 - Create: Bells & Whistles(bellsandwhistles)@0.4.3-1.20.x
 - Create: Steam 'n' Rails(railways)@1.5.3+forge-mc1.20.1
 - create: things and misc(create_things_and_misc)@1.0.0
 - Cristel Lib(cristellib)@1.1.5
 - Cumulus(cumulus_menus)@1.20.1-1.0.0-neoforge
 - Cupboard utilities(cupboard)@1.20.1-2.6
 - Curios API(curios)@5.7.2+1.20.1
 - Dank Storage(dankstorage)@5
 - Deep Aether(deep_aether)@1.20.1-1.0.2
 - DeepslateCutting(deepslatecutting_forge)@1.7.0
 - Default Options(defaultoptions)@18.0.1
 - Drippy Loading Screen(drippyloadingscreen)@3.0.1
 - Dungeons and Taverns(mr_dungeons_andtaverns)@3.0.3
 - Easy Emerald(easy_emerald)@1.4.15
 - Easy Piglins(easy_piglins)@1.20.1-1.0.1
 - Easy Villagers(easy_villagers)@1.20.1-1.0.17
 - Elevator Mod(elevatorid)@1.20.1-lex-1.9
 - Elytra Slot(elytraslot)@6.3.0+1.20.1
 - Emojiful(emojiful)@4.2.0
 - Ender IO(enderio)@6.0.25-alpha
 - EnderChests(enderchests)@1.20.1-1.2
 - EntityCulling(entityculling)@1.6.2
 - Everything is Copper(everythingcopper)@1.20.1-2.3.4
 - Experience Bug Fix(experiencebugfix)@46.2.2
 - Explorify(explorify)@1.3.0-mc1.20
 - Extreme Reactors(bigreactors)@1.20.1-2.0.77
 - Extreme Sound Muffler(extremesoundmuffler)@3.41-forge-1.20
 - FancyMenu(fancymenu)@3.1.2
 - Farmer's Delight(farmersdelight)@1.20.1-1.2.4
 - Farming for Blockheads(farmingforblockheads)@14.0.2
 - Flat Bedrock(flatbedrock)@3.0.1-build.18+mc1.20.1
 - flib(flib)@0.0.11
 - Flywheel(flywheel)@0.6.10-7
 - Forge(forge)@47.2.20
 - FramedBlocks(framedblocks)@9.2.1
 - Framework(framework)@0.6.27
 - GeckoLib 4(geckolib)@4.4.4
 - Guard Villagers(guardvillagers)@1.20.1-1.6.4
 - HopoBetterRuinedPortals(hoporp)@1.3.7
 - Immersive Paintings(immersive_paintings)@0.6.7+1.20.1
 - Industrial Foregoing(industrialforegoing)@3.5.14
 - Iron Chests(ironchest)@1.20.1-14.4.4
 - Iron Shulker Boxes(ironshulkerbox)@1.20.1-5.3.2
 - Jade Addons(jadeaddons)@5.2.2
 - Jade(jade)@11.7.1
 - Journeymap(journeymap)@5.9.18p1
 - Just Enough Items(jei)@15.3.0.4
 - Konkrete(konkrete)@1.8.0
 - Kotlin For Forge(kotlinforforge)@4.10.0
 - Let Me Despawn(letmedespawn)@1.2.0
 - Light Overlay(lightoverlay)@8.0.0
 - Lithostitched(lithostitched)@1.1.5
 - Lootr(lootr)@0.7.32.79
 - Macaw's Bridges - BOP(macawsbridgesbop)@1.20-1.1
 - Macaw's Bridges(mcwbridges)@2.1.1
 - Macaw's Doors(mcwdoors)@1.1.0
 - Macaw's Fences - BOP(mcwfencesbop)@1.20-1.0
 - Macaw's Fences and Walls(mcwfences)@1.1.1
 - Macaw's Furniture(mcwfurnitures)@3.2.2
 - Macaw's Furnitures - BOP(mcwfurnituresbop)@1.20-1.1
 - Macaw's Lights and Lamps(mcwlights)@1.0.6
 - Macaw's Roofs - BOP(macawsroofsbop)@1.20-1.0
 - Macaw's Roofs(mcwroofs)@2.3.0
 - Macaw's Windows(mcwwindows)@2.2.1
 - McJtyLib(mcjtylib)@1.20-8.0.3
 - Mekanism(mekanism)@10.4.6
 - Mekanism: Generators(mekanismgenerators)@10.4.6
 - Mekanism: Tools(mekanismtools)@10.4.6
 - Melody(melody)@1.0.2
 - Minecraft(minecraft)@1.20.1
 - Mining Gadgets(mininggadgets)@1.15.6
 - MixinExtras(mixinextras)@0.2.0-beta.9
 - Moonlight Library(moonlight)@1.20-2.11.4
 - Mouse Tweaks(mousetweaks)@2.25
 - MrCrayfish's Furniture Mod(cfm)@7.0.0-pre36
 - MyServerIsCompatible(myserveriscompatible)@1.0
 - Nature's Compass(naturescompass)@1.20.1-1.11.2-forge
 - Netherite Horse Armor(netheritehorsearmor)@1.20-1.5.0
 - NetherPortalFix(netherportalfix)@13.0.1
 - Nitrogen(nitrogen_internals)@1.20.1-1.0.7-neoforge
 - No Chat Reports(nochatreports)@1.20.1-v2.2.2
 - OAuth(oauth)@1.1.15
 - ObsidianUI(obsidianui)@0.2.1+mc1.20.1
 - Old Combat Mod(old_combat_mod)@1.1
 - OpenLoader(openloader)@19.0.3
 - Passthrough Signs(passthroughsigns)@2.6.3
 - Patchouli(patchouli)@1.20.1-84-FORGE
 - Pipez(pipez)@1.20.1-1.2.5
 - Placebo(placebo)@8.6.1
 - Polymorph(polymorph)@0.49.2+1.20.1
 - Polymorphic Energistics(polyeng)@0.1.0-1.20.1
 - Prism(prism)@1.0.5
 - Refined Polymorphism(refinedpolymorph)@0.1.0-1.20.1
 - Refined Storage(refinedstorage)@1.12.4
 - RFToolsBase(rftoolsbase)@1.20-5.0.2
 - RFToolsBuilder(rftoolsbuilder)@1.20-6.0.4
 - RyoamicLights(ryoamiclights)@0.2.1+mc1.20.1
 - Scuba Gear(scuba_gear)@1.0.6
 - Searchables(searchables)@1.0.2
 - SecurityCraft(securitycraft)@1.9.8
 - ShetiPhian-Core(shetiphiancore)@1.20.1-1.2
 - Silent Gear(silentgear)@3.6.0
 - Silent Lib(silentlib)@8.0.0
 - Simple Inventory Sorter(inventorysorter)@23.0.1
 - Simple RPC(simplerpc)@3.2.4
 - Sophisticated Backpacks(sophisticatedbackpacks)@3.20.3.1029
 - Sophisticated Core(sophisticatedcore)@0.6.11.578
 - SpectreLib(spectrelib)@0.13.15+1.20.1
 - Spice of Life: Carrot Edition(solcarrot)@1.15.1
 - Storage Drawers(storagedrawers)@12.0.2
 - Structure Essentials mod(structureessentials)@1.20.1-3.3
 - Structure Gel API(structure_gel)@2.16.1
 - SuperMartijn642's Core Lib(supermartijn642corelib)@1.1.17
 - TerraBlender(terrablender)@3.0.1.4
 - The Aether(aether)@1.20.1-1.3.0-neoforge
 - The Twilight Forest(twilightforest)@4.3.2145
 - Thermal Dynamics(thermal_dynamics)@11.0.0
 - Thermal Expansion(thermal_expansion)@11.0.0
 - Thermal Foundation(thermal_foundation)@11.0.2
 - Thermal Innovation(thermal_innovation)@11.0.0
 - Thermal Locomotion(thermal_locomotion)@11.0.0
 - Thermal Series(thermal)@11.0.2
 - Titanium(titanium)@3.8.27
 - Toast Control(toastcontrol)@8.0.3
 - Towns and Towers(t_and_t)@0.0NONE
 - TrampleNoMore(tramplenomore)@13.0.3
 - TrashSlot(trashslot)@15.1.0
 - Tree Harvester(treeharvester)@8.7
 - Trim Effects(trimeffects)@1.1.1-forge
 - Waystones(waystones)@14.1.3
 - Yeetus Experimentus(yeetusexperimentus)@2.3.1-build.6+mc1.20.1
 - YUNG's API(yungsapi)@1.20-Forge-4.0.4
 - YUNG's Better Dungeons(betterdungeons)@1.20-Forge-4.0.3
 - YUNG's Better End Island(betterendisland)@1.20-Forge-2.0.6
 - YUNG's Better Jungle Temples(betterjungletemples)@1.20-Forge-2.0.4
 - YUNG's Better Nether Fortresses(betterfortresses)@1.20-Forge-2.0.6
 - YUNG's Better Strongholds(betterstrongholds)@1.20-Forge-4.0.3
 - Zero CORE 2(zerocore)@1.20.1-2.1.41

**Comment by Tfarcenim** [comment]
There is no chance in hell I am finding it in that mess, in either case I made it easier to reassign ids.

**Comment by Garonne** [comment]
Where does DankStorage save it's Frequency Database? Because that's what seemingly seems to get lost each time I start the game? The Contents is saved, the fact Frequencies are already used is lost.

Test:
Creating Danks within game: Danks get assigned frequencies as they are supposed to... Starting with 0 increasing. If I try to reassign Frequencies (Frequency Textfield) frequencies are colored accordingly (yellow, green, blue).

Restarting the game, frequencies are assigned starting with 0 again. Trying to reassign frequencies yields orange for all frequencies that have not been re-assigned this game start. Frequencies regenerated within the current game session work as supposed.

Apparently the info, which frequencies have already been assigned are not stored properly.

Sorry, wasn't "All the Mods 10" (which is 1.21.1), but "All the Mods 9" (which is 1.20.1).

I assume DankStorage doesn't work well with one of the other mods... No Idea why.

Issue persists with Dank Storage 1.20.1-13 (Forge).
