### ISSUE TITLE
Crash when using dunk from other world

### ISSUE THREAD

**Issue by MineKool** [Tfarcenim/Dank-Storage#238]
if i load dunk from creative menu.... i lost fucking 17 worlds

**Comment by Tfarcenim** [comment]
1) No log

2) Most of the time saved data doesn't translate easily unless you know what you're doing.

**Comment by MineKool** [comment]
1.17.1
and.. i checking crash logs.... and nothing

**Comment by Tfarcenim** [comment]
Dank was never on 1.17, how did you load files from it?

> and.. i checking crash logs.... and nothing

I didn't say crash log, I said log, and there's always a log

**Comment by MineKool** [comment]
umm.... so.... dank from curseforge 1.17.1 not real?

**Comment by MineKool** [comment]
bro,i check every folder and even checked jar file of dunk and i cant find logs.... so what i can? 


or

_There nothing we can do_

**Comment by Tfarcenim** [comment]
> umm.... so.... dank from curseforge 1.17.1 not real?

It was never on that version.  I don't see how this is an issue on my end.
