### ISSUE TITLE
Dank docks hitbox bug

### ISSUE THREAD

**Issue by ADerpynarwhal** [Tfarcenim/Dank-Storage#239]
Found a small bug with the dock hitbox. The southeast corner(at least in my world) of all dock hitboxes is missing the middle section. The screenshot below shows me facing the wood block through the dock. 
![2024-03-23_17 16 05](https://github.com/Tfarcenim/Dank-Storage/assets/161911089/c2053239-72a3-462b-a7c1-ad8b165a2aa7)
This screenshot shows the hitbox when I hover over it. You can faintly see the horizontal lines at the top and bottom of the southeast column that indicate the edge of the hitbox border.
![2024-03-23_17 18 00](https://github.com/Tfarcenim/Dank-Storage/assets/161911089/81e6de00-7762-4c70-96c9-1dc771380327)

Not gamebreaking but is probably an easy fix
(Other three corners are correct)

**Comment by Tfarcenim** [comment]
Fixed in dev
