### ISSUE TITLE
Inventory moves and disappears when opened in UI and clicked on.

### ISSUE THREAD

**Issue by dbock1989** [Tfarcenim/Dank-Storage#24]
So as the title says, Im using the tier 6 Dank and when you open it and click on an item, the amount of every item you have changes and some disappear completely.  When you close it and reopen it, most of the time it goes back to normal, only to repeat when you click again but sometimes it just freezes the inventory that way.

Any Ideas?

**Comment by Tfarcenim** [comment]
mod version and pack if applicable

**Comment by dbock1989** [comment]
No problem
Mod version is newest one but did the same thing in last version and Im using "The New Frontier Reloaded" modpack

**Comment by Tfarcenim** [comment]
newest isn't very descriptive, I need the exact mod version so that I can reference kt later if I get a duplicate report

**Comment by dbock1989** [comment]
1.5a version

**Comment by Tfarcenim** [comment]
Having difficulty reproducing, is there a gif or something you can use to demonstrate the issue?

**Comment by dbock1989** [comment]
let me see if I can make one for you, Thank you so much again by the way

**Comment by dbock1989** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/33360899/66709666-0981da80-ed37-11e9-9cf7-307f6fd4ea69.gif)

**Comment by Tfarcenim** [comment]
this on a dedicated server by chance?

**Comment by dbock1989** [comment]
Yep my private server, you are welcome to join can I dm you on discord?

**Comment by dbock1989** [comment]
DBock#6048

**Comment by Tfarcenim** [comment]
nah, it's fine, figures since it looks like a syncing issue

**Comment by dbock1989** [comment]
alright so is it something that I can fix on the server then or am I kinda SOL?

**Comment by Tfarcenim** [comment]
it's something that I need to fix, shouldn't take too long

**Comment by dbock1989** [comment]
oh okay cool! Thank you so much!!!

**Comment by Tfarcenim** [comment]
well damn, wasn't able to reproduce on my own dev dedicated server, so there's a few possibilities remaining:

A) The bug only happens in release when on a dedicated server.

B) There's another (core)mod interfering with the containers

So I've got a fairly large pack that I can play that will help me narrow down the issues to see if it's possibly B, and A can be proven by induction.  Will be back in about an hour after testing.

**Comment by Tfarcenim** [comment]
results are in, it does not happen in adventures of halk which means this is a crossmod issue

**Comment by dbock1989** [comment]
I assume that means we are leaning on its another mod causing interference?

**Comment by Tfarcenim** [comment]
yes, a mod that's not in adv of halk but is in the new frontier.

**Comment by Tfarcenim** [comment]
best way to narrow it down is to clone the instance and start cutting mods.

**Comment by dbock1989** [comment]
This issue seems to be fixed in the latest update! Although I can not toggle to pick up, void or ignore items now. Although, I will open another ticket.
