### ISSUE TITLE
Crash when opening up Compact machine's UI with dank storage block thingy inside up

### ISSUE THREAD

**Issue by Fnige** [Tfarcenim/Dank-Storage#240]
Crash log: https://gist.github.com/Fnige/f8eee442bfa1e0b06c15b23d9005a3af

Im guessing you have to have a dank storage block with a dank inside it for a crash to happen but idk.

I would send this to CM but their issue reporting template sucks and this very heavily mentions dank so...

**Comment by ADerpynarwhal** [comment]
It would help if you were a little more descriptive with the bug. What were you doing prior to the crash? Is this bug easily repeatable? What was the setup of the mechanism you were using?

I will say, I read your log and it says near the top “dank instance null”. That makes me think you put an unassigned dank into a dock and tried to have something load the inventory, which wouldn’t exist yet. Did you?

**Comment by Tfarcenim** [comment]
Closing as OP has not responded with any details.
