### ISSUE TITLE
A "," is missing in zh_cn.json(1.20.1)

### ISSUE THREAD

**Issue by NoThInGter** [Tfarcenim/Dank-Storage#241]
![屏幕截图 2024-03-31 184905](https://github.com/Tfarcenim/Dank-Storage/assets/65540554/7cd2b6c5-5937-404d-97f8-8726fddf7d06)

**Comment by NoThInGter** [comment]
Also in fabric

**Comment by Tfarcenim** [comment]
fixed in 1.20.1-10
