### ISSUE TITLE
RMB oddity while in dank UI

### ISSUE THREAD

**Issue by nuclear200** [Tfarcenim/Dank-Storage#243]
MC Ver: 1.19.2
Mod Ver: 5.1.6
Test environment: found on stacia expert 2 pack and tested in an instance with just Dank Storage
Issue: RMB always tries to pick up 32 items not to split in half the current stack (which would be the expected RMB behavior) while in dank UI.
While in the Dank UI it affects both the dank inventory and the player inventory.

disregard if it is intended behavior

**Comment by Tfarcenim** [comment]
> Issue: RMB always tries to pick up 32 items not to split in half the current stack (which would be the expected RMB behavior) while in dank UI.

This is intentional to prevent pulling out oversized stacks, not a bug.
