### ISSUE TITLE
version 1.20.1-8 Dank_6 requires 4xcrying obby and 4x Amethyst blocks but the 5_to_6 upgrade only requires 8xobby

### ISSUE THREAD

**Issue by caineblood** [Tfarcenim/Dank-Storage#244]
version 1.20.1-8.jar, the default for 1.20.1 modpacks on curseforge has a different recipe for the Dank6 that requires 4 crying obby and 4 amethyst blocks; the upgrade to the same item only requires regular obby.

To replicate:

Make a new 1.20.1 curseforge modpack; add Dankstorage recommended version, add JEI or another recipie viewer mod
create new world in creative and look up Dank_6 and 5_to_6 and compare.

**Comment by Tfarcenim** [comment]
oversight fixed
