### ISSUE TITLE
Cant change ID with command or ingame button

### ISSUE THREAD

**Issue by owskie** [Tfarcenim/Dank-Storage#247]
On my server i created a dank then when another person made one it was the same as mine. I tried the unlock freq command and it didnt work. We realised there was a spot to change the freq in the dank but it would never change/save. when i try the change freq command it just says invalid ID. Im the admin and nothing works.

Any help is appreciated

edit: I'm playing Allthemods9

**Comment by Tfarcenim** [comment]
update to 1.20.1-10, it has a workaround

**Comment by owskie** [comment]
alright thank you
