### ISSUE TITLE
upgrade item works wrong in forge-1.20.1-10

### ISSUE THREAD

**Issue by feroooooo** [Tfarcenim/Dank-Storage#249]
version:forge-1.20.1-10
Upgrade item cant correctly upgrade the dank.
When use a 1 to 2 upgrade to dank 1, nothing happen. However, when use a 1 to 2 upgrade to dank 2, the dank 2 downgrade to dank 1.

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1-12
