### ISSUE TITLE
Locked Slots get cleared by Sort or Compress

### ISSUE THREAD

**Issue by Xetaxheb** [Tfarcenim/Dank-Storage#251]
Version 10, MC 1.20.1

Using the compress or sort features clears any locked slots and rearranges the contents.
Likewise, sorting should only sort unlocked slots and leave locked slots where they are and locked.

Ideally, it would only compress to matching items or matching locked slots, or when an empty slot is available if shift is held while clicking compress.
Say I have a dank 1 and AllTheCompressed meaning: cobble(x0), cobble x1(cobble\*9), x2(x1\*9 or 81) ,x3, x4, etc
If I had locked slots x0,x1,x2,x3 but had 6561 cobble (equivalent to one x4) and clicked compress, it would compress into x0->x1->x2->x3 but not into ->x4 because I had no matching item nor matching locked slot (only x3\*9 blocks). 
If I held shift while clicking instead, assuming I had a free unlocked slot, it would go up to x4\*1 (or higher if i had more and space).
If i had only locked slots/matching items x0,x1,x2,x4 but not x3, it would go up to x2\*81; unless I held shift in which case it would go to 1\*x4.

**Comment by Tfarcenim** [comment]
Locked slots are no longer cleared on sorting in 1.20.1-11, however compressing rearranging contents is intentional to keep the code simple and bug free.  Compress has never supported shift clicking.
