### ISSUE TITLE
[1.20.1][Fabric] Stacktrace in console, then dank dissapeared from players inventory.

### ISSUE THREAD

**Issue by ProsperCraft** [Tfarcenim/Dank-Storage#253]
https://gist.github.com/ProsperCraft/7ab6e7cc53ca95e2b59866f516b88ff8

Dedicated server
dankstorage-fabric-1.20.1-12

Modlist- https://gist.github.com/ProsperCraft/2b03dcb22c8aeae62d0914ba5f9c2dda

**Comment by Tfarcenim** [comment]
Fixed in 1.20.1-13
