### ISSUE TITLE
Feature Request: AE2 cell workbench integration

### ISSUE THREAD

**Issue by piotao** [Tfarcenim/Dank-Storage#254]
Describe the feature
It will be nice to add an integration between Dank Storage and Cell Workbench in Applied Energistics2 mod. AE2 allows to format disks for storing items in variable capacity with a few rows of  items, depending on tier. Cell workbench would allow to format itself in "copy mode" to reflect Dank Storage content, to allow to create disks formatted with the content of Dank Storage container.

Reasons why it should be considered
This will be nice because Dank is similar to Portable Cell and the functionality is similar. I would like to move content from many danks to disks, because Danks when are emptied, do not store their previous content because they are incapable of storing saved item types (like disks from AE2 do).

This feature request is also submitted to AE2 feature request. I hope you find this idea good enough to implement!

Thank you for the awesomeness and the coolest mods ever seen in Minecraft!

AE2 mod:
https://appliedenergistics.org/
https://github.com/AppliedEnergistics/Applied-Energistics-2
https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2

**Comment by Tfarcenim** [comment]
Cool idea, but out of scope.
