### ISSUE TITLE
Dank Null ID duplication

### ISSUE THREAD

**Issue by linaraincalzando** [Tfarcenim/Dank-Storage#255]
Minecraft Version 1.20.1
Fabric Version 0.14.23

When crafting new danks if you have danks in filtered mode the new danks will have an ID already in use.

**Comment by linaraincalzando** [comment]
Restarted my game and even with all danks had filtered mode disabled IDs are duplicating again.

**Comment by Tfarcenim** [comment]
what mod version?

**Comment by linaraincalzando** [comment]
Looks like its fixed in the latest version!
