### ISSUE TITLE
1.21.1 with Fabric 0.16.2 Danks unable to hold more than 64 items

### ISSUE THREAD

**Issue by hugenull** [Tfarcenim/Dank-Storage#257]
I created a new mod set to test with just Cloth Config API, Fabic API, and Dank Storage and even one a fresh single player world you drop the stacks in the dank it shows the item count and if you close it and open it back its back to 64. I also tested on the larger Danks with the same result. 

![image](https://github.com/user-attachments/assets/de969cda-1e19-4211-98a5-ea327b29b7f1)

**Comment by Tfarcenim** [comment]
fixed in 1.21-4
