### ISSUE TITLE
Crash when open a dank after update from neoforge 1.21-3 to 1.21.1-5

### ISSUE THREAD

**Issue by Moshanxi** [Tfarcenim/Dank-Storage#263]
After update my dank can't pick up anything, so I open it to check, then crash.
[crash-2024-09-06_14.36.59-server.txt](https://github.com/user-attachments/files/16903895/crash-2024-09-06_14.36.59-server.txt)

**Comment by Tfarcenim** [comment]
Known, not getting fixed.
