### ISSUE TITLE
[1.21.1] crash arter open menu

### ISSUE THREAD

**Issue by Rumaruka** [Tfarcenim/Dank-Storage#264]
After opening the menu in dank, it crashed:
[crash-2024-09-10_14.14.49-server.txt](https://github.com/user-attachments/files/16942456/crash-2024-09-10_14.14.49-server.txt)

**Comment by volrathstormborn** [comment]
Same issue here with v1.21.1-5  Was fine empty, but after opening to set options for filtered pickup or pull items directly the client crashes.
[latest&debug.zip](https://github.com/user-attachments/files/17134846/latest.debug.zip)

**Comment by Tfarcenim** [comment]
Fixed in 1.21.1-7
