### ISSUE TITLE
Server Crash - Ticking Entity

### ISSUE THREAD

**Issue by Darkfiend009** [Tfarcenim/Dank-Storage#265]
Server crashed while reorganizing my level 3 Dank. Took all the items out and was proceeding to put them back in.

Crash Report: https://gist.github.com/Darkfiend009/3f1754ff0875f1b477da4da497044a56

Minecraft: 1.21.1
Neoforge: 21.1.42
Dank Storage: 1.21.1-5

**Comment by Darkfiend009** [comment]
Here is a similar crash. This occurred when i clicked "auto sort" in the options of the Dank GUI.

https://gist.github.com/Darkfiend009/43503431df30f267b222d0d7451d1e78

**Comment by Tfarcenim** [comment]
Does this happen on a fresh world, the issue looks like you upgraded from an older version which won't work because of breaking changes.

**Comment by Darkfiend009** [comment]
The server and world were created on September 9th so it wouldn't be an upgrade from an older version, unfortunately.

Once i finally got everything out of and then put back into the dank, things have been working fine.

I did upgrade the dank in game from 2 to 3 while it had materials still inside it. Not sure if that could cause an issue.

**Comment by Tfarcenim** [comment]
Fixed in 1.21.1-7
