### ISSUE TITLE
Dank Storage mod adds a a Forge tag that messes with assisted progressions crusher

### ISSUE THREAD

**Issue by CrankySupertoon** [Tfarcenim/Dank-Storage#27]
Basically the crusher from assisted progressions turns 1 iron ore into 2 Ruby’s. Now before you say wrong mod I believe it’s at your fault since sits checking and all the items seem to have a forge tag for this mod so it’s cycling between them. Sorry if I sound unclear I’m taired when righting this

**Comment by Tfarcenim** [comment]
doubt it
