### ISSUE TITLE
[1.21.1-8] Breaking a dock with a dank in it will cause the dank to lose its frequency and then that frequency will no longer exist.

### ISSUE THREAD

**Issue by clyons-dev** [Tfarcenim/Dank-Storage#270]
So I was using the docks to fill my danks with a bunch of items, and after I finished I used my pickaxe to break the docks and get the danks out. This caused all of their frequencies to be reset back to -1 and when i tried to set the frequency back to their original ones, its was orange indicating the frequency doesnt exist.

**Comment by clyons-dev** [comment]
Okay, I dont know if thats a bug, and i found the proper way to get the danks out. Is there a way to go and unlock those frequencies through commands or through the .dat files?

**Comment by Tfarcenim** [comment]
Yes, it can be done through using a /give command with the correct data, what version is this?

**Comment by clyons-dev** [comment]
Oops, my bad i forgot to add it in the title. Fixed it, but its [1.21.1-8]

**Comment by clyons-dev** [comment]
Thank you so much for the help, i did the /give and i got them back.

**Comment by Tfarcenim** [comment]
Fixed in 1.21.1-9
