### ISSUE TITLE
Why does your mod add malicious code similar to the code of the Tinkers / Greg incident.

### ISSUE THREAD

**Issue by furtabs** [Tfarcenim/Dank-Storage#271]

**Comment by furtabs** [comment]
For anyone reading this @Tfarcenim's mod is purposelly flagged to be incomaptible with fabric bridges, beacuse he wants no. Not because it isn't. This is pretty malicious as so put by the Sinytra discord.

**Comment by Tfarcenim** [comment]
Because I've had too many incidents with it breaking my own mods, it's not malicious at all.  If you really feel like dealing with the issues that come with it instead of simply using the forge or fabric version then feel free to fork it and deal with the issues yourself.
