### ISSUE TITLE
Item display desync when using dank in off-hand

### ISSUE THREAD

**Issue by Arkaeic** [Tfarcenim/Dank-Storage#274]
Title pretty much sums it up.

Mod Version: latest
Game Version: 1.12.1

How to replicate:
Put a 1 of a block in the dank, place the dank in your off hand and you'll see that you can place blocks infinitely until the dank is removed from the off-hand. The graphic that shows how much of the current item is remaining will not decrease as you'd expect it to when placing items.

**Comment by Tfarcenim** [comment]
It's not an actual dupe bug, but a desync when items are used from the offhand, this can be seen by opening the dank after placing a bunch of blocks..

**Comment by Tfarcenim** [comment]
Fixed in 1.21.1-11
