### ISSUE TITLE
Cannot link dank to existing frequency

### ISSUE THREAD

**Issue by randymac** [Tfarcenim/Dank-Storage#278]
We recently upgraded our server from 1.21 to 1.21.1 and went from version 4 to 12 of dank storage.  Afterwards we deleted all the old danks and created new ones, but we were not able to link 2 danks to the same frequency, with teh freq always showing orange for 'freq does not exist'.  I also made a new test world with only dank storage installed and had the same issue.  Is it a bug?

Thanks for this great mod.

**Comment by Tfarcenim** [comment]
Known, unfortunately in this case it's a breaking change so there isn't much that can be done.

**Comment by randymac** [comment]
OK just to clarify this feature wont be coming back? To be clear im not trying to get back old freq, im trying to link 2 new ones.

**Comment by Tfarcenim** [comment]
Linking to an existing frequency is possible if it's unlocked, if it's not working on a new world with the latest mod version then open a new issue report.
