### ISSUE TITLE
I cannot change pick up with "p"

### ISSUE THREAD

**Issue by dbock1989** [Tfarcenim/Dank-Storage#28]
Everything seems to be working great now except I can no longer toggle pick up modes. I am on version 1.9 of Dank-Storage and on version 2.9 of The New Frontier Reloaded modpack.

"i" works for changing from bag, chest, construction, but "p" doesnt do anything now, and there is no change for it in the .ini

**Comment by Tfarcenim** [comment]
pick up modes have been moved to the gui as of 1.6 to save on keybinds
![java_2019-10-20_13-17-37](https://user-images.githubusercontent.com/44327798/67163362-fcb74500-f33b-11e9-9414-6c5b6d74b463.png)

**Comment by dbock1989** [comment]
Alright so I just found that I have a search bar blocking the UI... If I click in the spots that are shown on the mod page, I can filter through them. So again, it is a mod interference issue. Since I cant see the pick up but I can click it, what do the colors represent?  There is a green glow, a yellow glow and a red glow.

**Comment by dbock1989** [comment]
I assume its, pick up all, pick up inside items only, and void mode?

**Comment by Tfarcenim** [comment]
correct.

**Comment by dbock1989** [comment]
I really appreciate that, I was reading another persons issue when I saw you said you removed "p", So I went back into game and started playing with it and did find that the search bar that is added from some other mod blocks the UI completely. Glad to know its not an issue with your mod considering its now my favorite mod for MC.
![image](https://user-images.githubusercontent.com/33360899/67163427-b9a9a180-f33c-11e9-9b2e-8b46cf912597.png)
