### ISSUE TITLE
Add items to already existing stacks

### ISSUE THREAD

**Issue by RakSrinaNa** [Tfarcenim/Dank-Storage#31]
When items are inserted into the dank through a pipe/hopper, items are not added to existing stacks (and so doesn't go to locked spots for it). Could be great if it'd behave like the item pickup (#12).

Mod version: 1.13a
Forge: 28.1.92

**Comment by Tfarcenim** [comment]
I want to redo the container system, but that won't be possible until 1.15 due to the nature of the changes I'd have to make so this will be saved until then.

**Comment by Tfarcenim** [comment]
I tried and it wouldn't be possible without messing with other mods
