### ISSUE TITLE
Unable to Customize recipes via Datapack

### ISSUE THREAD

**Issue by Nachtflame** [Tfarcenim/Dank-Storage#33]
Title pretty much says it all, trying to overwrite recipes via a datapack for my modpack with ~~no~~ little result.  
I use **DRP - Global Data Pack** [by JTK222] in my modpacks for getting datapack info loading in player created worlds, and it creates/uses a folder at .minecraft\global_data_packs\ for this purpose. 
I've found that if I put the datapack files into the _saves\ {world}\datapacks_ folder, then I can change only the "minecraft:crafting_shaped" recipes, not the special block-upgrade recipes.  
My biggest issue with that method is making players take extra steps outside the game to get the _intended recipes_ for a modpack.

I understand the need for special recipe handlers when dealing with items that _**will definitely**_ have .nbt tags in the 1.13+ systems, ~~but could there be a method available for customizing those recipes?~~ [see comment below]

Dank Storage  1.13a
Forge 28.1.104
globaldatapack-1.14.4-1.2.1

**Comment by Nachtflame** [comment]
After further testing, I've found that CraftTweaker actually provides customization capability for at least the normal recipes.  You're custom recipe types don't show up with /ct dumpBrackets (which generates a file listing all recognized recipeTypes).

**Comment by Tfarcenim** [comment]
hmm, the recipes are hardcoded because I didn't think anyone would want to tamper with them, and I have not found a way to make them datapack friendly

**Comment by Tfarcenim** [comment]
got it

**Comment by Nachtflame** [comment]
I'm one of those "Pack Author" weirdos that really likes fiddling with things... Notably one that insists on conformity to his own sense of "balance/accessibility" guided by the theme of the pack. 😁

Thanks for the fix!
