### ISSUE TITLE
[1.14.4] Picking up a placed Dank w/ CarryOn makes you stuck.

### ISSUE THREAD

**Issue by Gbergz** [Tfarcenim/Dank-Storage#34]
Heya,
Picking up a placed Dank Storage w/ Carry-On it makes you stuck, you can't do ANYTHING while in this state. You can't place it down, you can literally not do anything.
Only solution is to kill yourself with a command or natural cause.

MC-Version: 1.14.4
Forge Version: 28.1.107
Dank Version: 1.15? This one: [https://www.curseforge.com/minecraft/mc-mods/dank-storage/files/2844644](https://www.curseforge.com/minecraft/mc-mods/dank-storage/files/2844644)

Anything that can be done to prevent them from being picked up by CarryOn? I've tried adding the block ids of the Danks in its config blacklist but that didn't work at all.

**Comment by Tfarcenim** [comment]
do those take tile ids or block ids, I don't remember, but check the main mod class for them.

I resolved this issue in 1.15.x but there's nothing I can do about 1.14 because there's too great of a danger of breaking existing saves
