### ISSUE TITLE
[1.15.1] Error Message: Install Mixin

### ISSUE THREAD

**Issue by realTIMematrix** [Tfarcenim/Dank-Storage#36]
Hi,

i created a new profile for 1.15.1 with latest Forge 30.0.41 and install Dank Storage 2.4 only and get the following message: Install Mixin

[https://pastebin.com/RFMaWvVV](url)

Version 2.2a works fine, but not your latest version.

If you need additional infos please send questions.

best regards

**Comment by Tfarcenim** [comment]
yep, you need to install mixin, that error message is intentional https://github.com/LXGaming/MixinBootstrap/releases/download/v1.0.1/MixinBootstrap-1.0.1.jar

drop it in the mods folder on server and client

**Comment by davenonymous** [comment]
Can you improve the error message? People don't understand "install mixin".
I'd suggest: "DankStorage requires the Mixin bootstrap mod. Download the mod from https://github.com/LXGaming/MixinBootstrap/releases/"

**Comment by realTIMematrix** [comment]
> Can you improve the error message? People don't understand "install mixin".
> I'd suggest: "DankStorage requires the Mixin bootstrap mod. Download the mod from https://github.com/LXGaming/MixinBootstrap/releases/"

BTW the author of mixinbootstrap Upload the file to the curseforge Page. So if you Made ist as Requiered dependancy ist should be loaded in a modpack
