### ISSUE TITLE
1.15.1 Crashing Server

### ISSUE THREAD

**Issue by Millificent** [Tfarcenim/Dank-Storage#39]
Hello,

Reporting a crash on server associated with Dank Storage
Report: https://s.yoosk.pl/U8BoC

MC v:1.15.1
Forge v: forge-30.0.43
Jar v: dankstorage-2.4a.jar

Options used: only filtered tier 3.

**Comment by Tfarcenim** [comment]
can't seem to trigger the crash, how to reproduce

**Comment by Tfarcenim** [comment]
yeah, no it's not my mod, the only reason it's mentioning my mod is because it modifies that class, but I don't touch anything in the stacktrace.

**Comment by Tfarcenim** [comment]
something about falling blocks is triggering an endless loop to update neighbors

**Comment by Lavan** [comment]
I have the same issue, caused while using the "Just Not Enough Mods 2" pack. I guess I'll have to look through the mod-list to see what might be the cause.

**Comment by Lavan** [comment]
An update, the pack included the Fast Leaf Decay mod which does have an updated version. The error hasn't been seen since I updated.
