### ISSUE TITLE
Game crash while trying to open chest/storage.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [Tfarcenim/Dank-Storage#4]
When trying to open tier 1 dank storage chest game crashes. Forge 1.14.4-28.0.81

Crash log:
https://www.dropbox.com/s/fqzujjjphpnywe5/crash-2019-09-01_18.36.36-client.txt?dl=0

**Comment by Tfarcenim** [comment]
This is caused by optifine, nothing I can do about that.
