### ISSUE TITLE
Forge Loading Screen Loop

### ISSUE THREAD

**Issue by jkwphysics** [Tfarcenim/Dank-Storage#43]
Hard to be 100% sure if it is Dank Storage, but I've tried numerous mod selections in a pack together and removing Dank Storage is the only thing that prevents this from happening.  After the pre-loading "deep scan" screen, the loading bar following that loops forever and the client never fully starts.

Highlighted section from log:
https://pastebin.com/gjC42MuW

full log:
https://pastebin.com/7qk1DUc5

I've also tried forge versions going back to 31.1.9 but I start to get "required version" errors earlier than 31.1.14 so didn't go much farther.  Forge 31.1.9 did not have the loading screen loop problem with this mod, but then I wasn't actually able to launch with the other mods I needed so it wasn't a good solution.

I look forward to playing this this mod; it looks pretty awesome!  Hope this helps if anyone else is having the same issue.

**Comment by Tfarcenim** [comment]
the solution is listening to the error and installing mixin.  It is unfortunate that it's not included in forge at this time, but there isn't an alternative as the features that this provides are not possible without it.
