### ISSUE TITLE
Infinite load time else "install mixin"

### ISSUE THREAD

**Issue by usafphoenix** [Tfarcenim/Dank-Storage#45]
So if dank storage mod is added to a 1.15.2 modpack containing a bunch of mods, it will completely fail to load, or crash. it cycles infinitely on the loading screen. If a new modpack is created with ONLY dank-storage mod it will quickly fail and say to install "mixin". Twitch Launcher does not detect this as a necessary dependency and so, when adding the mod to an installation, does not download mixin-bootstrap1.0.2, but a manual search and install does fix this second installation.

The problem is ISOLATING the issue when building the modpack, it won't crash, and the user has to KNOW that mixin bootsrapper is what is required because i don't think the dependency was declared properly to the twitch mod portal ....thingy.

**Comment by usafphoenix** [comment]
(note that adding mixin-bootstrap fixed both installations) but the issue here is it fails to crash/give an error message if loaded with too many other mods, and will just fail to load the screen or error message, and twich won't auto-install the mod it currently requires

**Comment by Tfarcenim** [comment]
can't do much about this
