### ISSUE TITLE
[BUG] Or possible compatability issue with explosions & cyclic mining dynamite.

### ISSUE THREAD

**Issue by 0xebjc** [Tfarcenim/Dank-Storage#46]
#### SETUP
Mincraft: 1.12.2
Forge: 14.23.5.2847
Dan-Storage: 1.12.2-1.4-pre11
Cyclic: 1.12.2-1.19.21

### ISSUE
When blocks are destroyed by explosion, Dank Chests disappear, the are not returned as drops.

I was testing this with Cyclic mining dynamite.

### EXPECTED BEHAVIOR
When destroyed by explosions, the are returned as a drop with all nbt data containing items stored inside.

Or, better yet, I would recommend making them blast proof and not destroyable by explosions.

**Comment by Tfarcenim** [comment]
Explosions only return 1/power of the number of blocks that they break in 1.12, are you sure this is an actual bug and not a vanilla mechanic?  Either way, 1.12 is no longer supported for nonfatal issues (aka, anything other than crashes/corruption).
