### ISSUE TITLE
Construction Keybind as Mouse Button Not Updating

### ISSUE THREAD

**Issue by FenixFyreX** [Tfarcenim/Dank-Storage#47]
Dank Storage v2.6 - 1.15.2

If the keybinding for changing modes is set to a mouse button (middle, forward, back, etc), the mode doesn't actually change until a key on the keyboard is pressed. Mouse buttons seem to fall under `MouseInputEvent`, not `KeyInputEvent`, so perhaps subscribing to both and calling the logic from a common handler if necessary?

**Comment by Tfarcenim** [comment]
not an issue anymore in 1.16.1
