### ISSUE TITLE
[Request] Shift-click to move a single stack to inventory (or configurable behavior)

### ISSUE THREAD

**Issue by chimericdream** [Tfarcenim/Dank-Storage#48]
Currently, if you shift-click a stack in the DS, it will attempt to empty the entire contents of that slot into your inventory. While this is sometimes useful, I find myself more often wanting to move only a few stacks.

Perhaps this would be a viable solution (not sure how easy keybinds like this are to implement):

* Empty Dank slot into your inventory (Shift+click)
* Move 1 stack from Dank slot into your inventory (Ctrl+Shift+click)

If you make the default keybinds work like above, it keeps the existing behavior but allows people the option to override.

I'm loving the mod. Thank you!

**Comment by Tfarcenim** [comment]
single click does that already

**Comment by chimericdream** [comment]
Single click picks up a stack yes, but say you want to move 10 stacks. You have to pick up one at a time and manually place it into your inventory. What I'd prefer, if it's feasible, is the ability to hold shift and click 10x on the slot in the dank and have one stack at a time moved straight to open slots in my inventory.
