### ISSUE TITLE
OpenGL Error: 1284 (Stack underflow) on hotbar selection

### ISSUE THREAD

**Issue by CyanSlinky** [Tfarcenim/Dank-Storage#5]
Whenever i select a dank in the hotbar it outputs this to the console:
"OpenGL Error: 1284 (Stack underflow)"

mod version : 1.4-pre1 to 1.4-pre4
forge version : 28.0.83

now i know that this is probably due to optifine and most mod devs don't bother with it / can't do anything about it but i figured I'd report it anyways. And it also used to not output this message in version 1.3a (with optifine as well). 

I just really want the construction ability, which seems to be from 1.4 and onwards? so i hope this can be fixed.

Edit: the error also seems to only appear when there's something in the dank.

**Comment by Tfarcenim** [comment]
it has to do with the rendering of the item in the slot, there is nothing I can do about this since optifine is closed source software so I can't see what is causing the issue and fix it.

**Comment by CyanSlinky** [comment]
yeah i figured as much, maybe you could have a hotkey or setting to toggle the item preview thingy. Or find some other way to show it. If not no worries, i know optifine can be problematic.

**Comment by Tfarcenim** [comment]
added a toggle until optifine stops breaking things.

**Comment by CyanSlinky** [comment]
thanks, that's probably the best/only solution for now; I guess you can consider this closed.

**Comment by RepoDraghon** [comment]
Where is the toggle? I'm having this issue too...
