### ISSUE TITLE
Problem causing items in danks disappear

### ISSUE THREAD

**Issue by ChromaPIE** [Tfarcenim/Dank-Storage#51]
1. Fill a dank with some random items
2. Put it in the Shipping Container from BDS&M
3. Attach a piece of ME Storage Bus from AE2 to the Shipping Container and link it to the ME Terminal with ME cables.
4. Now problems appears but you won't suffer any loss. The problem is when opening the Terminal, things in the Dank can't be displayed on the GUI, but if you stop doing anything except taking the Dank out of the Shipping Container, you are all fine, things stays where they should be. It's also useless to break and re-install the Storage Bus, the Terminal, and the cables.
5. What's worse, trying to put **anything** into the Dank via the GUI of the Terminal will cause **all of the items in the Dank disappear**, irreparable.

**Comment by Tfarcenim** [comment]
1.12 is dead
