### ISSUE TITLE
Using Construction mode causes a stack underflow error in OpenGL. 

### ISSUE THREAD

**Issue by krlsmnk** [Tfarcenim/Dank-Storage#52]
Playing on 1.14, single player world. Tried both of the latest mod versions for 1.14; same problem on both.

Switching a dank to construction mode while holding it, or swapping to one already in construction mode, prints to the console:
"OpenGL Error: 1284 (Stack Underflow)"

Performance also becomes choppy while holding a dank in construction mode. Unsure if it's just the framerate, or the game itself struggling. Let me know how I can get more information to you if you need it. 

No crashes, and everything still works correctly, but errors with storage mods can go badly fast. 

Happens with every size dank (except maybe the Nether Star one; haven't tested yet). Happens regardless of pickup mode

**Comment by Tfarcenim** [comment]
1.14 is dead
