### ISSUE TITLE
1.16.1 version 3.2

### ISSUE THREAD

**Issue by closeshot** [Tfarcenim/Dank-Storage#54]
Getting a crash with this error when trying to open the dank storage

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: tfar.dankstorage.client.screens.AbstractAbstractDankStorageScreen.renderTooltip(Lcom/mojang/blaze3d/matrix/MatrixStack;Ljava/util/List;IILnet/minecraft/client/gui/FontRenderer;)V

**Comment by Tfarcenim** [comment]
fixed in 3.2a
