### ISSUE TITLE
1.16.1 - dank 3.2a

### ISSUE THREAD

**Issue by bessiq** [Tfarcenim/Dank-Storage#55]
Hi,

First of all, thanks for porting dank to 1.16. And for pushing updates so quickly! 3.2a no longer crashes the game client (yay), but I found another issue: if you right-click a dank onto a dock that already has a dank in it, the old dank disappears, including any contents in it. Would it be possible to check for an existing dank in the dock, and either pop it out or not allow the held dank to be docked until the docked dank is removed? Man, that was a weird-sounding sentence to type.

Anyway, if you need more info just let me know. This was on Forge 32.0.63 btw.

**Comment by Tfarcenim** [comment]
I'm going to implement a swapping behavior

**Comment by Tfarcenim** [comment]
fixed in 3.3
