### ISSUE TITLE
1.16 mod incompatibility w  telekinesis mod

### ISSUE THREAD

**Issue by Knito58** [Tfarcenim/Dank-Storage#56]
The enchantment "telekinesis" which sucks the mined items directly into the player's inventory does stop the pickup of items as that items never are dropped into the world.

(solved by uninstalling telekinesis atm)

**Comment by Tfarcenim** [comment]
Time for another coremod

**Comment by Tfarcenim** [comment]
hmm, that won't work, there's nothing I can do on my end.

**Comment by Tfarcenim** [comment]
belay that, there might be something

**Comment by Knito58** [comment]
Just wanted to let you know about this. This is not a bug in my eyes. But some users might say "your mod no sucks item, dah!". And you now know possibly why.

**Comment by Tfarcenim** [comment]
fixed in 3.4, items are now intercepted from any source trying to add to player inventory.

**Comment by Knito58** [comment]
Fix confirmed. Very good work. Telekinesis + Dank = Lots of fun. No more worries if that diamonds will drop into the lava pool or not.
