### ISSUE TITLE
Severe Dup Glitch and possible feature add

### ISSUE THREAD

**Issue by UnhallowedDeath** [Tfarcenim/Dank-Storage#58]
So i just found this out. In the 3.4 and i'm assuming previous versions. But since you have it so the Dank nulls stack this causes a dupe glitch. If you have 2 or more stacked you can put any item in it and when you split the stack each of the dank nulls will have that item. For example I make 10 of the Dank1 because their so cheap. I have them stacked and i put one diamond in it. i then separate the stack and now I have 10 diamonds. I then restack and put the 10 diamonds in then unstack. I now have 100 diamonds. you can do this with any item that goes into the dank nulls. Including the dank nulls them self's since you can put dank nulls inside each other.  

To resolve this the easiest thing to do would to make it so the stack size for them is 1. Also being able to place a dank null inside another serves no purpose currently that i can see.  I can think of two things to do with this. Easiest would be to make it so they can't be put inside other dank nulls. Or (and i would love this option)  Have is so they work inside each other. 

For example.   
In Dank 1 on pickup and I have - Cobble, Dirt, Gravel, Sand, Granite, Diorite, Andesite
In Dank2 on pick up/void and I have - All the ores, Diamond Emerald, Coal, redstone, Lapis
In Dank3 on pickup  I have all my crops.

If i take thoes 3 dank nulls and put them inside a forth Dank null. An i have that dank null on Pickup. Then if i pick up cobble it will actually go into dank1. If i pick up ore it will go into Dank2. If i pick up food it will go into dank3.

**Comment by Tfarcenim** [comment]
dupe bug is gone
> Have is so they work inside each other.
concern

**Comment by UnhallowedDeath** [comment]
Hello. I just wanted to thank you for fixing the dupe glitch.  I also wanted to clarify the working inside each other.   Are you saying that it Should be working inside each other? Or that having it that way is a concern. Just looking for a clear Answer. 

Also I looks like the Pickup all option does not work any longer. from testing it looks like "Pickup All" and "Filtered" Only allow the dank null to pick up items that are already inside the dank null.   Is the "Pickup all" supposed to cause the dank null to pick up any item even if its not in the dank null? For example. 

Dank1- Pickup all - Slot 1 i have Coal.  Even though it only has coal in it should it still pickup stone that i mine as long as there's an empty slot in the Dank Null?

**Comment by Tfarcenim** [comment]
I can't seem to reproduce it

**Comment by UnhallowedDeath** [comment]
Which are you referring to?

**Comment by UnhallowedDeath** [comment]
I was trying to upload a gif and accidentally hit close. Unfortunately I'm not able to upload a .gif or video here. is there somewhere i could upload to show you

**Comment by Tfarcenim** [comment]
> is there somewhere i could upload to show you
the discord server
> Which are you referring to?

> Also I looks like the Pickup all option does not work any longer. from testing it looks like

**Comment by Tfarcenim** [comment]
https://discord.gg/vZxnfa4

**Comment by UnhallowedDeath** [comment]
I think i found the issue. The most recent one on curse when i updated was version 3.5. I just checked and it looks like theres 2 other versions. I just went to version 3.7 and it all seems to be working. Im sorry for the misunderstanding. I looks like versions 3.6 and 3.7 were not on the launcher when i updated.

Though as far as them working inside each other. That still does not work. But like i said i wasn't clear on if that was something that would be added or not.  Feel free to close this since it is no longer an issue. Or let me know and i can close it

**Comment by UnhallowedDeath** [comment]
Hello Im playing with version 3.7. It looks like there's still some kind of issue with filtered pick up. adding a video to show. when set to filtered the dank null acts like it picked it up. but when you open the dank null the number has not increased

**Comment by UnhallowedDeath** [comment]
Closing because there is another issue for the same thing
