### ISSUE TITLE
[Suggestion] Selecting the block with pick block keybind

### ISSUE THREAD

**Issue by WhitePhant0m** [Tfarcenim/Dank-Storage#59]
With a big dank that has a lot of different blocks it becomes harder to find the specific block you are looking for, so if you could look at a block and press the key bind for pick block you would select the block you are looking at from your dank if you have that block type in there.

**Comment by Tfarcenim** [comment]
fixed pickblock not working with mouse in 3.7

**Comment by VendoAU** [comment]
Could you make it so when you use pick block when not holding the dank it will switch to holding it?
I'd be willing to make a pull request if you'd like.
