### ISSUE TITLE
Having the dank block in off hand can delete items

### ISSUE THREAD

**Issue by BuzzWilson** [Tfarcenim/Dank-Storage#6]
The dank block will delete itself or ghost when in offhand with construction mode on. This can also delete the item in the main hand.

MC Version: 1.12.2
Forge Version: 14.23.5.2838
Dank Storage Version: 1.4-pre6

**Comment by Tfarcenim** [comment]
Working on it, but it's taking a bit because I'm refactoring everything to consider the offhand as well.

**Comment by Tfarcenim** [comment]
Added offhand functionality in 1.12.2 for 1.4 prerelease 7, still need to do this for 1.14

**Comment by Tfarcenim** [comment]
fixed in 1.14 as well
