### ISSUE TITLE
Client crash when interacting with inventories

### ISSUE THREAD

**Issue by KrAzYGEEK32** [Tfarcenim/Dank-Storage#61]
MC version: 1.16.1
mod version: 3.7a
 issue: client seems to crash (sometimes) when interacting with inventories.
 crash report:
[crash-2020-08-06_13.18.26-client.txt](https://github.com/Tfarcenim/Dank-Storage/files/5034429/crash-2020-08-06_13.18.26-client.txt)

Tbh i didnt know it was dank storage causing the issue, i was redirected here from pneumaticraft git, i thought it was their issue and posted it there, the told me to check with dank storage, hope the crash report help :)

**Comment by Tfarcenim** [comment]
It's an issue with productive bees, not dank storage.

>     at cy.jdkdigital.productivebees.item.Gene.func_77624_a(Gene.java:75) ~[?:1.16.1-0.2.2] {re:classloading}
>     at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:579) ~[?:?] {re:mixin,re:classloading,xf:fml:quark:add-spacing-for-stack,pl:mixin:APP:dankstorage.mixins.json:ItemStackMixin,pl:mixin:A}
>     at me.desht.pneumaticcraft.client.gui.GuiItemSearcher$SearchEntry.<init>(GuiItemSearcher.java:289) ~[?:1.16.1-2.0.0-4] {re:classloading}
