### ISSUE TITLE
[1.15] Problems when interacting with the refined storage external storage bus

### ISSUE THREAD

**Issue by Ste1e** [Tfarcenim/Dank-Storage#62]
I'm playing the Q-tech pack, minecraft version 1.15.2, dankstorage-2.6.jar, and refinedstorage-1.8.8.jar

When connecting an external storage bus to a dank storage and having it as a priority to the system over the drives all items will be inserted into the dank storage, regardless of it being locked. 

When trying to extract items, there are weird interactions within the grid. Sometimes you can pull out some items, while other times you cannot. There doesn't seem to be a connection between whether the items are in the dank storage or if they are in a drive and if you can pull them out through the system, though the items in the dank storage were more likely to be extractable.

In many cases I could extract a single stack and then no more, while the grid showed no change in total item quantity but when I exited the grid I kept the items and the screen updated.

crafting the redstone blocks into redstone seemed to have no issues..

for replication I have all dank storage tiers lined up with a 2 stacks of stone, iron, oak planks, cobblestone and redstone each. a drive with 2 64k storage disks filled with 8 stacks of stone, redstone, redstone blocks, birch saplings, stripped spruce wood, and gold ore. I attached an external storage to each dank storage separately and gave them a priority of 10.

**Comment by Tfarcenim** [comment]
Fixed in 3.12a
