### ISSUE TITLE
[1.16] ctrl lock button not working

### ISSUE THREAD

**Issue by ghost** [Tfarcenim/Dank-Storage#63]
Title sais all

**Comment by refhub** [comment]
This might be a conflict with Inventory Essentials.
I was able to work around it by disabling  single transfer from inventoryessentials-client.toml.

>#Should ctrl-clicking only move one item at a time instead of the full stack?
>enableSingleTransfer = false

**Comment by Tfarcenim** [comment]
figures

**Comment by Kolv81** [comment]
I am getting this issue too but  Inventory Essentials is not installed

**Comment by Beckfast1994** [comment]
I am also not able to lock the dank slots with ctrl. I even tried with only the dank mod and it's a no go :/

**Comment by xSnufflesx** [comment]
I also had this issue even with only the dank storage mod installed

**Comment by RevenantWendigo** [comment]
Can we please get a keybind option for this? It is such critical functionality and it has been bugged for months.

**Comment by CatLuvrs54** [comment]
> I am getting this issue too but Inventory Essentials is not installed

Same here. Minecraft 1.16.5, forge 36.1.65, dank storage 3.16 with no other mods installed. It still does not work. Perhaps a laptop vs pc issue? I'm on a windows 10 laptop; I have to use ctrl to use the function keys in game (for instance, ctrl f3 for the screen with coords and whatnot, as f3 alone simply raises my screen brightness level).

**Comment by theebs** [comment]
(version 3.16)
The tooltip might be unclear. It says "Press ctrl to Lock", which implies just pressing the ctrl only to lock that slot. However, after a lot of trial and error, I found holding ctrl and left clicking the slot to work.

**Comment by CatLuvrs54** [comment]
> (version 3.16)
> The tooltip might be unclear. It says "Press ctrl to Lock", which implies just pressing the ctrl only to lock that slot. However, after a lot of trial and error, I found holding ctrl and left clicking the slot to work.

Sadly not the case for all of us.

**Comment by Tfarcenim** [comment]
This is no longer the case in 1.18 as I turned the lock button into a proper keybind
