### ISSUE TITLE
[1.16] Crash when opening an upgraded dank

### ISSUE THREAD

**Issue by freevortex** [Tfarcenim/Dank-Storage#64]
I used a 1 -> 2 upgrade on a dank placed in the dock. I then broke the dank/dock, picked up the dank, and tried to open it, which caused an immediate crash. Upgrading a dank in the dock and then trying to right click it in the dock also causes a crash. The dank had items in it. I have Optifine installed, if it matters. 

Relevant section of the log here: https://pastebin.com/GXcHVg1A

**Comment by Tfarcenim** [comment]
fixed in 3.8
