### ISSUE TITLE
[1.16.2] Crash on block left click

### ISSUE THREAD

**Issue by Askadar** [Tfarcenim/Dank-Storage#66]
When trying to destroy any block with dank (level 2, red) equipped minecraft crashes.
Forge version 33.0.21, latest dank version 3.9.

Crash log attached [crash-2020-08-28_19.51.21-server.txt](https://github.com/Tfarcenim/Dank-Storage/files/5143246/crash-2020-08-28_19.51.21-server.txt)

Workaround: drop forge version to *33.0.20*.

**Comment by Askadar** [comment]
Most likely same crash when right clicking empty space (no block highlighted)

Another log [crash-2020-08-28_20.03.11-server.txt](https://github.com/Tfarcenim/Dank-Storage/files/5143289/crash-2020-08-28_20.03.11-server.txt)

Block placing and bag mode works.

**Comment by Askadar** [comment]
Seems to be linked to .21 forge update [changelog](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.2-33.0.21/forge-1.16.2-33.0.21-changelog.txt)

- **Added a new implementation of map(), which returns Optional<T>, and resolves the value in the process.**

Works on forge *33.0.20*

**Comment by Tfarcenim** [comment]
yep, I need to fix that and clean up some code.
