### ISSUE TITLE
Various

### ISSUE THREAD

**Issue by ArturilloD** [Tfarcenim/Dank-Storage#67]
Is there any possibility to unite the features of terrible chest (https://www.curseforge.com/minecraft/mc-mods/terrible-chest) and dank storage? (By the features I mean basically those on the main screen of terrible chest)

The morph-o-tool key (https://www.curseforge.com/minecraft/mc-mods/morph-o-tool) cannot act from inventory.

It would be nice to be able to implement the option to eat in construction mode and implement a creative mode, that is, that the elements are never finished and be able to copy the block with its content by doing ctrl + central click.

**Comment by Tfarcenim** [comment]
Eh, dank storage is already broken enough as it is, it doesn't need a creative mode.
