### ISSUE TITLE
Crash when trying to upgrade

### ISSUE THREAD

**Issue by angelnc1989** [Tfarcenim/Dank-Storage#7]
https://paste.dimdev.org/isotawefin.mccrash

**Comment by Tfarcenim** [comment]
attempted to address this in prerelease 8

**Comment by Tfarcenim** [comment]
if it still happen, can you reproduce it in a world with as few mods as possible so I can be sure a coremod is not breaking things

**Comment by angelnc1989** [comment]
I think the crash only happens with FastWorkbench plus another mod I haven't identified installed.
Only JEI + Dank Storage -> no crash
with FastWorkbench -> dupes the Dank item

I will try and figure out which mod is causing the crash.

**Comment by Tfarcenim** [comment]
Found the issue, fixing now
