### ISSUE TITLE
Shift Clicking items into a dank storage inventory causes them to be erased next time you open the dank storage

### ISSUE THREAD

**Issue by Rarvey** [Tfarcenim/Dank-Storage#70]
Storing items individually with the mouse works fine but Shift clicking to quick deposit a stack leads to that stack not being saved in the dank storage. Reproduced on version 3.10a

**Comment by Tfarcenim** [comment]
Can't reproduce, need more context

**Comment by Rarvey** [comment]
Steps to reproduce:
1. Place any number of a block (like dirt) in a dank storage. 
2. Close dank storage. 
3. Reopen dank storage and shift click more of that same item from your inventory, adding to the stack in the dank storage.
4. Close dank storage.
5. Reopen dank storage and the shift-clicked amount added in step 3 is gone. The amount of block is back to where it was after step 1.
