### ISSUE TITLE
[1.16.1] Game Crash - Clicking on the Dank Dock with a Mekanism Configurator 

### ISSUE THREAD

**Issue by NielsPilgaard** [Tfarcenim/Dank-Storage#71]
**Version**
- dankstorage-3.8

**Modpack version**
Enigmatica6 0.2.16

**Issue**
While it's not that likely to open, it is still possible that someone might click with the Meka Configuration Tool on a Dank Dock.
The game crashes as per the attached log.
This issue was reported by Nunbear on Discord, and I was able to replicate it.

**Logs**
https://gist.github.com/Ridanisaurus/d2fa4995e8c4c32f7d4322fd0e33b78f
https://gist.github.com/Ridanisaurus/5689415a410b6f7616e2edeacb175164

**Comment by Tfarcenim** [comment]
I fixed this in one of the 1.16.2 versions, but I'll see if it's possible to backport the fixes.

**Comment by NielsPilgaard** [comment]
Don't bother for my sake, we're moving to 1.16.2/3 asap anyway :) thanks!
