### ISSUE TITLE
[1.16.3] Mod interaction crash - When in a dank storage if you trash something to the trash slot, it crashes

### ISSUE THREAD

**Issue by ProsperCraft** [Tfarcenim/Dank-Storage#75]
https://github.com/blay09/TrashSlot/issues/82

**Comment by andrewsf** [comment]
Has not been fixed by TrashSlot despite the status of the linked issue.

Filed blay09/TrashSlot#83

**Comment by flenrydev** [comment]
For me it crashes when my mouse simply goes over the trash slot while using a dank

**Comment by Tfarcenim** [comment]
Fixed on my end
