### ISSUE TITLE
The Mode button doesn't work

### ISSUE THREAD

**Issue by daAresinger** [Tfarcenim/Dank-Storage#77]
The game tooltip asks you to hit key.keyboard.*whatever key* but it doesn't actually work.

**Comment by Benjamin-Berry** [comment]
I'm seeing "key.keyboard.unknown" in the tooltip and I don't see anything in the key config screen. "hey.tanknull.mode" is in only thing bound to i.

**Comment by Tfarcenim** [comment]
see if this is still an issue on 3.13
