### ISSUE TITLE
Minecraft keeps on crashing!

### ISSUE THREAD

**Issue by JohnPone** [Tfarcenim/Dank-Storage#78]
My game keeps on giving me an exit code 1. the log says its because of a mixins.json file issue. Here's a copy of the full log...

14:05:37.868
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler$$Lambda$365/936219350.accept(Unknown Source)
14:05:37.868
[java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.HashMap.forEach(HashMap.java:1280)
14:05:37.868
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
14:05:37.868
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
14:05:37.868
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
14:05:37.869
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
14:05:37.869
[java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
14:05:37.869
[java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.IllegalArgumentException: The specified resource 'dankstorage.mixins.json' was invalid or could not be read
14:05:37.869
[java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1082)
14:05:37.870
[java.lang.ThreadGroup:uncaughtException:1061]: 	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
14:05:37.870
[java.lang.ThreadGroup:uncaughtException:1061]: 	... 20 more
14:05:38.521

Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
14:05:38.522
Process crashed with exit code 1

**Comment by Tfarcenim** [comment]
that's not the full log

**Comment by JohnPone** [comment]
[2020-11-22-3.log.gz](https://github.com/Tfarcenim/Dank-Storage/files/5586199/2020-11-22-3.log.gz)
[latest.log](https://github.com/Tfarcenim/Dank-Storage/files/5586201/latest.log)

**Comment by Tfarcenim** [comment]
that is really odd, going to chalk it up to a corrupted file
