### ISSUE TITLE
Breaking items that drop while hold dank storage in construction mode deletes item

### ISSUE THREAD

**Issue by choekstr** [Tfarcenim/Dank-Storage#80]
MC: 1.16.4
Pack: TNP Limitless 3 1.8.0
Forge: 35.1.4
Dank: both 3.0 and 3.11a

When I break an item that drops (flowers, sugar cane, cactus, etc) and the dank storage is in construction mode with both Tag and Pickup red colored (seems like tooltips are not showing now so not sure what mode that is) the item immediately disappears and is destroyed.  If I take the dank storage out of construction mode it drops normally to the world.  This is either with or without the items in the dank storage: meaning if I put sugar cane in dank storage the next broken sugar cane is voided and the count remains the same in the dank storage.

Items that drop other items, like grass for seeds or pams gardens are not affected as it's a new item dropped.

**Comment by mellamokb** [comment]
I can confirm I have the exact same issue.  On TNP Limitless 1.7.5 and Dank Storage 3.11.

**Comment by Tfarcenim** [comment]
fixed in 3.13
