### ISSUE TITLE
Quark Dupe Glitch

### ISSUE THREAD

**Issue by RoyalReject** [Tfarcenim/Dank-Storage#81]
If you lock an item in the storage and use quarks easy transferring feature to remove items it will keep the item locked and still remove blocks allowing anything to be duped including single stack items.

**Comment by Tfarcenim** [comment]
Not sure how I missed this one, anyways, it's a bug in quark, not dank.  I have disabled their buttons on my inventories until they fix it.  https://github.com/Vazkii/Quark/issues/2507
