### ISSUE TITLE
"Chest Mode" missing on 1.16.2 Fabric (All of Fabric Modpack)

### ISSUE THREAD

**Issue by ThorToddson** [Tfarcenim/Dank-Storage#82]
All features of Dank-Storage seem to work except DSUs will not go into Chest Mode.  Bound key will transition from Construction to Bag modes only.

Great Mod - even without Chest Mode!

**Comment by Tfarcenim** [comment]
intended, use a dock, also wrong github https://github.com/Tfarcenim/DankStorageFabric/issues
