### ISSUE TITLE
NBT size weirdness

### ISSUE THREAD

**Issue by aaronhowser1** [Tfarcenim/Dank-Storage#88]
![](https://cdn.discordapp.com/attachments/166630061217153024/787223371720818708/unknown.png)
![](https://cdn.discordapp.com/attachments/166630061217153024/787223395565043742/unknown.png)
![](https://cdn.discordapp.com/attachments/166630061217153024/787223418822721546/unknown.png)

Then I close and reopen and its 207 again

**Comment by Tfarcenim** [comment]
fixed in 3.13
