### ISSUE TITLE
Ticking entity 1.16.4

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Tfarcenim/Dank-Storage#89]
###Version Information
Minecraft: 1.16.4
Forge version: 35.1.12
Dank Storage version: 3.12
###Further Information

Not sure what happened. I was notified the server was down and found Dank Storage listed. Wish I could offer more information.

https://pastebin.com/XB02P00J

**Comment by Tfarcenim** [comment]
3.12b fixes this
