### ISSUE TITLE
Issue with hotbar scrolling and item switching

### ISSUE THREAD

**Issue by cacione** [Tfarcenim/Dank-Storage#9]
Hi there, i have two issues with using this mod. 
Issue 1 is when i crouch and scroll through the hotbar the selection stops on any Donk Storage in the hotbar. Even when the Donk Storage isn't in construction mode.
Issue 2 is with Donk 6, and maybe some others. When sorting item stacks it doesn't switch the items in hand with the items in the Donk Storage. Any stack bigger than 64 isn't switched with.

**Comment by Tfarcenim** [comment]
fixed in both versions
