### ISSUE TITLE
forge server 1.14.4 with 28.2.23 forge version

### ISSUE THREAD

**Issue by krusis11** [Tfarcenim/Dank-Storage#90]
after installing forge server and adding dank storange mode and mixinbootstrap the mod doesnt work. can see recipe after adding all recipies. i can get item in creative mode but this „chest” wont open, cant switch to construction mode and the „chest” disapears after opening normal chest. any other mod works fine.

**Comment by Tfarcenim** [comment]
Sorry, can't do anything as versions of this mod older than 1.16 are EoL and I don't have the spare time to pursue them.
