### ISSUE TITLE
Dank storage won't void items 

### ISSUE THREAD

**Issue by AwkwardOne** [Tfarcenim/Dank-Storage#91]
It keeps letting items take in multiple spaces instead of just voiding them after filling one up?

**Comment by Tfarcenim** [comment]
Is it on void pickup?

**Comment by AwkwardOne** [comment]
> Is it on void pickup?

I don't see such a feature anywhere, the Button changes the modes between construction and pickup. In the UI itself there's the tag button, sort button and pickup button. The first one changes between red and green when pressed while the pickup button has a yellow inbetween, however using the yellow one doesn't change anything for me. I'm using a mining laser with magnet upgrade from the Direwolf20 mod Mining Gadgets

**Comment by AwkwardOne** [comment]
I see, the red one was the void pickup all along, red kinda communicates off so you might wanna find a way to communicate that better. Having little tags on the buttons that say what they do would be nice

**Comment by Knito58** [comment]
I have the same problem when the dank is in the dock. Then it won't void when the hopper wants to put items into it, resulting in blocking the whole system.

I played with the buttons of the dank but whatever I do, the dock seems to say "Stop!" to the hopper.

-> This happens on a server. Didn't see that in single player.

**Comment by Tfarcenim** [comment]
>  Then it won't void when the hopper wants to put items into it
Intentional, the dock is not a trash can

**Comment by Knito58** [comment]
Surely it is not a trashcan. I thought I would use the voiding mechanism to simplify the setups of my farms.
This would have been too easy, I see.

Ok, I'm gonna use the garbage bin mod for overflow and some more pipes.
