### ISSUE TITLE
[1.16.4] Ability to remove dank storage from the dock without breaking it?

### ISSUE THREAD

**Issue by xinitrc-dev** [Tfarcenim/Dank-Storage#92]
I'm not sure if I'm missing something, but I don't seem to be able to remove dank from the dock besides breaking said dock. Would be really nice if I could just right click on pop it out or smth. Let me know if this is already implemented and Im just missing it :)

**Comment by OnesAndZer0s** [comment]
Shift Right Click with an empty hand
