### ISSUE TITLE
Dank Internal Buttons based on Relative Name Position

### ISSUE THREAD

**Issue by desagas** [Tfarcenim/Dank-Storage#94]
# Description
When you rename a Dank, any level from what I have seen, the "tag" and "pickup" buttons will move around according to that given name, which means, even naming it something like "Dank Mobs," which should fit, moves the buttons to a place where they can not be clicked because of the "sort" button, which is conveniently absolutely positioned or snapped to the right side of the GUI.

## Expected Behavior
Like the Sort Button, which is awesome, the tag and pickup buttons should be absolutely positioned or snapped beside the Sort Button to always remain beside Sort, the way it does naturally, without remaining a Dank. Thus, the name of the Dank then should be given only the remaining space, and be truncated with "..." when too long for the space to handle.

![Screen Shot 2021-01-02 at 1 02 09 PM](https://user-images.githubusercontent.com/8404632/103465604-beb4ff80-4cfa-11eb-9d96-53111eba900e.png)

**Comment by Tfarcenim** [comment]
This will be fixedish in 1.18
