### ISSUE TITLE
[1.16.4] Render Bug (Only Renders Center Cube)

### ISSUE THREAD

**Issue by Zedrimar** [Tfarcenim/Dank-Storage#95]
Ok, I have actually no idea about this one. It appears like it does not render properly and just renders the cube inside for some unknown reason (at least to me it is). I was worried for a bit that maybe NVidia GPUs rendered things weird, but I guess not. Ran with both the iGPU (i7 1075H) and the following discreet GPUs: RTX 2070, GTX 1660 TI. All seem to cause this weird glitch. I do not know of any render settings that could also cause this as I generally tend to leave the NVidia control panel alone unless something is broken. Funny enough, the "tank null" mod also has a similar weird thing to it. Any thoughts? I know it definitely isn't my computer just being a potato so I am honestly curious now what caused this because I also had the same issue with the dank null mod back in 1.12. I know it's definitely not some weird RAM thing because the laptop I am writing this on has 16 gigs and my PC has 32. Besides that, I have no idea what is causing this. I just thought for a while that forge is broken. Maybe I'm just doing something wrong?

Mods needed: N/A (dank storage only)
Forge: 35.1.28

Here is also some debug info (forced crash): https://pastebin.com/X3HEwtqp
Tested on Asus Zephyrus M15
Also tested on PC with the following parts: https://pcpartpicker.com/user/Zedrimar/saved/9N3j23

PS: Yes I know in this case I had optifine installed, but I only had it to see if maybe the way optifine renders things would fix it, but that never happened. Just ignore the rest of the mods, they had no effect. I had indeed tested this with just forge and dank storage and the same thing happened. Also, I normally don't use optifine (unless I want fog gone), so I know it's not optifine doing the exact opposite of what I wanted to try. Even with fabulous graphics setting it still is borked

Screenshots: 
![2021-01-02_16 05 15](https://user-images.githubusercontent.com/8153290/103469302-e5356380-4d17-11eb-9b13-11847be5c634.png)
![2021-01-02_16 05 49](https://user-images.githubusercontent.com/8153290/103469303-e6669080-4d17-11eb-90c5-d96c3ea512cf.png)

**Comment by Tfarcenim** [comment]
That's intentional to separate the dank from the dock.

**Comment by Zedrimar** [comment]
Oh.... Huh, my brain is dead then. Thanks for clearing that up
